### ISSUE TITLE
[実装] - ネットワーク版　通常攻撃

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#205]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
追記：

オフライン版で作っていたプレイヤー2人が交互にする攻撃を実装して欲しいです。
実際にプレイして確認が取りたいので今メインで使っているシーンに反映しておいてください。

2人でプレイして問題無く動作とボスへのダメージが確認できたら承認します。

**Comment by Saki223** [comment]
完了しました。攻撃の発生、持続、硬直fに関してはAssets>Prefab>PlayerのPlayerAttackから調整してください
