### ISSUE TITLE
[実装] - ネットワーク版　プレイヤーの移動

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#256]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
追記：

オフライン版で制作していたプレイヤーの移動の実装をオンラインでもできる状態にしてください。
・プレイヤーの方向の回転（見た目含む）
・相方のプレイヤーの画面での位置動機
まで確認できたら承認します。

**Comment by Saki223** [comment]
完了、確認おねがいします

**Comment by okamoto0102** [comment]
報告ありがとうございます。確認しました。
ちゃんと操作はできたのでが、いくつか直しが欲しい所があります。
こちらの指示にも問題があったと思うので、
要件を記載しておきます。

・キャラクターの方向の回転
┗現状ずっと右向きなので画面左に移動する時には左向きになるようにしてください。
・上方向に移動する際にアニメーションが再生されていない
┗その時に向いている方向の向きでアニメーションをさせてください。
・ビルドデータ側での問題
┗もう片方のプレイヤーの位置動機は問題ないけどアニメーションの再生がされていない

現状確認できた問題は以上なので、リスケの期限等はまた相談ください。

**Comment by Saki223** [comment]
でけた
