### ISSUE TITLE
[実装] - ネットワーク版　ボスの攻撃

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#258]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
攻撃アニメーション、SE実装完了
プレイヤーに攻撃が当たった時にお札が減る実装完了
確認お願いします。

**Comment by okamoto0102** [comment]
確認しました。報告ありがとうございます。
Unityのエディタでは問題なかったのですが、
ビルドデータの方でダメージを受けた時に消える
お札のアイコンがずれていました。
一番右側から消えるようにお願いいたします。
リスケの調整をするので、期限等はまた相談ください。
