### ISSUE TITLE
[実装] - リザルト画面のシステム

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#263]
### タスクの目的

リザルトシーンを作成する。

### タスクの詳細内容

■リザルトへのシーン切り替え
ボスが撃破される→ボスの撃破エフェクト→ふすまが閉まる（ローディング演出）→リザルトシーン
リザルトの接続は維持したままでお願いします。

■リザルトシーンに配置するボタン
・メニュー
　┗部屋名を入れる画面に遷移。遷移時に接続を切る
・もう一度
　┗接続をそのままで同じステージを再プレイ
・次へ
　┗接続はそのままで次のステージをプレイ

### 期待される結果

接続はリザルト画面までは維持で、
部屋のリーダー（ホスト）が選択したものによって接続の切断か否かを判定する感じにしてある。

### 締め切り

ガントチャートで調整

### 補足情報

配置レイアウト等は仕様書に記載

**Comment by MiyoshiTaishou** [comment]
今日からリザルトシーンの作成を取り掛からないといけないんですが仕様書まではいかなくても
必要な処理があればここに書いといて欲しいです。
一応画面遷移処理は実装できてます。
通信は切断する形のシーン遷移です。

**Comment by okamoto0102** [comment]
ボスのIssue出しをしたので、そちらを優先して貰っていいでしょうか？
それでもリザルトのIssue事態は、今日中にあがるように動いて貰っています！

**Comment by okamoto0102** [comment]
@MiyoshiTaishou 
記入終わったとのことなので確認よろしくお願いします。

**Comment by MiyoshiTaishou** [comment]
仮のリザルトシーン作成

**Comment by MiyoshiTaishou** [comment]
通信を維持したままリザルト遷移処理実装
接続を切って部屋名を入れる画面に遷移処理実装
同じステージ再プレイ処理実装
二つ目のステージが無いのでまだ入れてませんが処理自体はほぼ完成してるのですぐに対応できます。

確認お願いします。

**Comment by MiyoshiTaishou** [comment]
スコア表示の処理の実装完了
ホストとクライアントで表示するUI変更完了

確認方法
Title_Networkからゲーム開始（チュートリアルシーンでしか処理を適用させていないため）
ボス倒す
リザルト画面に遷移（ホストなら狸、クライアントなら狐になっています）

ゲームの開始の判定をチュートリアルシーンに配置しているGameManagerで管理しています。
インスペクターで何人になったら開始するか変えれます。

コンフリクトが怖いのでまだビルドシーンには適用していません
確認お願いします。

**Comment by MiyoshiTaishou** [comment]
揃ったらゲームの開始を判定できるようになったのでメンバー揃うまでふすまが開かないようにしたり
スコア表示の演出をTimeLineを使ってより豪華にするなどブラッシュアップ出来る箇所が多くあるなと
思ったのでそのあたりの実装をどうするか相談したいです。

僕の見積もりだと揃うまでふすまが開かないは一日あれば実装出来ます。

TimeLineなどでスコア表示の演出を豪華にするとかは提案としてはtextにmaskしてmaskをずらして左から表示したり
Tegetaをハンコを押したみたいなSEを入れてactiveにしたりするだけでもかなり変わるように思います。
こちらはプランナー側でどんな演出にしたいなどあると思うのでそこが固まり次第実装かなと思ってます。
二日ほどあれば実装はできると思います。

**Comment by okamoto0102** [comment]
提案ありがとう！
今週はα版の調整作業と３ボスの検討を優先するので、
来週の頭位に検討する時間を考慮したスケジュールにしておきます！

**Comment by okamoto0102** [comment]
@morikaito 
自分の方ではリザルトシーンへの以降確認できました。
そちらでも確認できたらDoneに移動お願いします。
ブラッシュアップの部分は相談して、β版の作業に回した方が良いと思うので別でIssueを提示してください！
