### ISSUE TITLE
[実装] - プレイヤーHP関連の処理

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#265]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Saki223** [comment]
完了、確認おねがいします

**Comment by okamoto0102** [comment]
確認しました。報告ありがとうございます。
Unityのエディタでは問題なかったのですが、
ビルドデータの方でダメージを受けた時に消える
お札のアイコンがずれていました。
一番右側から消えるようにお願いいたします。
リスケの調整をするので、リスケの期限等はまた相談ください。。

**Comment by okamoto0102** [comment]
失礼、お札が減る処理は担当が違うみたいなのでそちらにお願いします。
他は問題ないのでこちらのIssueは閉じます。
