### ISSUE TITLE
[実装] - 予備動作用の仮エフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#271]
### タスクの目的

α版に向けて、予備動作のエフェクトが出る処理の作成

### タスクの詳細内容

ボスの攻撃が出る数フレーム前に予備動作として目が光るようなエフェクトが出る処理をお願いします。
参考資料です
![Image](https://github.com/user-attachments/assets/440470e8-03f5-47e3-b705-c59b6a0db7f1)

### 期待される結果

上記の内容が不備なく実装できており、プランナーが調整できること。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

エフェクトの出るタイミングは調整できるようお願いします。

**Comment by MiyoshiTaishou** [comment]
前のタスクが既に完了しているようなので開始日を早めます
今日から作業になるので作業中に変えてください

**Comment by MiyoshiTaishou** [comment]
今日が締め切りですが進捗どうですか
ボスの攻撃に関係する部分なのでBossAttackActionを変更掛けたりするのかなと思ってますが
平井君もそのスクリプトに変更掛けると思うので二人で連絡とってコンフリクト起きないようにしてください

**Comment by mathuki-takumi** [comment]
現在タイミングがどうしても上手く調整できないので、エフェクトを出すタイミングをアニメーションと同期させられないか試しているところです。今晩中には完成すると思います
了解しました、変更の際には連絡するよう気を付けます

**Comment by MiyoshiTaishou** [comment]
進捗どうですか
間に合わなさそうなら報告ください
原因次第では僕も協力出来るかもしれません

**Comment by mathuki-takumi** [comment]
一晩試したんですが、アニメーションのフレーム側で特定の処理を呼び出すやり方はインスペクター側での細かい修正ができなさそうだったのでBossAI側でタイミング調整する形に戻しました

BossAIのインスペクター側に『攻撃の予兆に関する項目』という箇所が増えてます
そこで『ボスの攻撃前エフェクト』と、『攻撃モーションに移行してからエフェクトを出すまでの秒数』を調整できるようになってます
エフェクトに関してはNoneになっていると思うので、実行の際にはマージシーンのBoss2D→BossAIの上記の項目にエフェクトを入れてから試してみてください

**Comment by MiyoshiTaishou** [comment]
確認したんですけど目が光っているように見えませんでした
そちらで動いている場合は動画かスクショお願いします。

**Comment by mathuki-takumi** [comment]
確認ありがとうございます
再度修正し、下記のスクショの位置にエフェクトが出る点確認しましたので、他機でも同じように動作するか確認お願いいたします
パーティクルはHovl Studio内にある『Fast Charge slash red』を設定して検証しました
![Image](https://github.com/user-attachments/assets/b75fdfd6-23d3-4486-9089-c2e63403e04f)
![Image](https://github.com/user-attachments/assets/c3caa8ec-60a1-4320-b734-d1f4ecc927bd)

**Comment by okamoto0102** [comment]
会議で報告した内容の修正を引継ぎをお願いします

**Comment by mathuki-takumi** [comment]
インスペクター側でX,Y座標の数値変更できるよう変更いたしましたので確認お願いいたします

**Comment by mathuki-takumi** [comment]
@okamoto0102 
インスペクター側でX、Y座標の数値変更できるようにいたしましたので確認お願いいたします

**Comment by MiyoshiTaishou** [comment]
確認出来ましたか
報告お願いします

**Comment by okamoto0102** [comment]
申し訳ないですが、ビルドデータで確認したいです！
ビルドシーンに反映までお願いします！

**Comment by mathuki-takumi** [comment]
確認漏れすみません、ビルドのマージシーン側に反映しましたので再度確認お願いいたします

**Comment by okamoto0102** [comment]
ありがとうございます!
今日遅くまで外出してるので明日の午前中には確認いたします!

**Comment by okamoto0102** [comment]
ありがとうございます！
ビルドデータでも確認できました！
