### ISSUE TITLE
[実装] - ボスの攻撃エフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#272]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
未承認のままです！動画かスクショを添付して
コメントで進捗の報告をお願いします！

ビルドシーンへのマージが必要ならその旨の報告もコメントでお願いします！

**Comment by mathuki-takumi** [comment]
エフェクト実装終わりましたので確認お願いします
お手数おかけしますが、Marge SceneのBossAttackAreaのインスペクター側にあるBoss Attack Area スクリプトにAttack Particleという項目がありますので、そこにパーティクルを設定してからの確認お願いいたします

**Comment by okamoto0102** [comment]
ホスト側でもでる時と出ない時があるので、
原因救命と対応をお願いします。

**Comment by mathuki-takumi** [comment]
@okamoto0102 
ホスト側にてボスの向いている方向にエフェクトが出る点確認しましたので、確認お願い致します

**Comment by okamoto0102** [comment]
了解です！確認します！

**Comment by okamoto0102** [comment]
OKです！確認します。できましたので、Doneに移動しておきます。
