### ISSUE TITLE
[実装] - メインゲームのUIシステム

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#279]
### タスクの目的

プロトタイプに向けて仮の素材を使って
メインゲームのUIの配置、UIごとのシステムを実装して頂きたいです。

### タスクの詳細内容

このIssueは大雑把な期限なので各種UIごとに別でIssueを割り振ります。

### 期待される結果

期限中に各種UIが実装されている状態。

### 締め切り

10/25(金)　終日

### 補足情報

タスク完了後に微調整はするので、画面構図通りに配置物を置いてくださると助かります。

**Comment by okamoto0102** [comment]
Issue内容を更新しました。
ご確認よろしくお願いします。
■仕様書
┗https://docs.google.com/spreadsheets/d/1o_tra0iHjsfij-bYmWHp4nMajjOoSt5Y/edit?gid=1714262927#gid=1714262927

**Comment by okamoto0102** [comment]
![Image](https://github.com/user-attachments/assets/2c2dd8e0-3054-46d6-a195-7ce79c67f3d5)

**Comment by MiyoshiTaishou** [comment]
UI配置完了
それぞれのUI毎の処理は別のIssueらしいのでほとんど配置しただけです。
確認お願いします。
これも金曜日に言うの忘れてた
