### ISSUE TITLE
[実装] - ヒットストップのシステム

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#283]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

■必要だと思う箇所
・通常攻撃
・パリィ成功時
・必殺技
・撃破時
・ボスのダウン

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Saki223** [comment]
想定される使用箇所のみ書かれていて仕様の部分が不明瞭なので実装内容の提案をします

・停止対象は自身のみ(例：プレイヤーの通常攻撃ヒット時、プレイヤーは停止するが敵は停止しない)
・停止するものはオブジェクトの座標、再生中のアニメーションとパーティクル
・停止時間の調整方法はInspecterViewにて個別に設定
・停止時間の単位はf(60/sec)

問題なければ上記の内容で実装します

**Comment by Saki223** [comment]
必殺技後にヒットストップ理由がわからないです。
必殺技の演出後のヒットストップってのはプレイヤーを停止するのかボスを停止するのかどちらですか？
そもそも、ヒットストップというのは攻撃などが「ヒット」した時に発生する停止時間なので、撃破時であったり必殺技の演出後に停止時間をかけるにしても別の処理になると思います

**Comment by okamoto0102** [comment]
指摘ありがとう!
考え直したら確かに必殺技ヒットストップ必要無いと思うので無しで大丈夫です。

他にいらなさそうな所とかあればまた言ってください

**Comment by Saki223** [comment]
了解です。

**Comment by Saki223** [comment]
通常攻撃、パリィにヒットストップを実装しました

**Comment by okamoto0102** [comment]
今、エフェクトと一緒に確認しています。

**Comment by okamoto0102** [comment]
各停止時間はPlayerAttack、PlayerParryNetで調整可能です

**Comment by MiyoshiTaishou** [comment]
残り実装項目

・溜め攻撃のヒット時
・連携攻撃のヒット時

**Comment by Saki223** [comment]
・ボスの撃破時
・ボスがダウンする瞬間

これらに関しても「ヒット」ストップではないため、必要であれば別で処理を組んだ方が良いと思いますがどうですか？

**Comment by okamoto0102** [comment]
@Saki223 
ご指摘ありがとうございます。
エフェクトが実装されてきて爽快感は感じますし、他に優先事項ありますので
無しで大丈夫です！

引き続きよろしくお願い致します！

**Comment by okamoto0102** [comment]
残りのヒットストップが実装待ちになるのでそちらは別でスケジュール立てますが大丈夫でしょうか？

**Comment by Saki223** [comment]
よかです

**Comment by okamoto0102** [comment]
わかりました。
直近のスケジュールなので早急に対応します。

**Comment by okamoto0102** [comment]
残りの作業はまた別でIssue提示しましたのでこちらDoneに移動しておきます。
