### ISSUE TITLE
[UI素材] - コンボゲージ

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#293]
### タスクの目的

コンボの表記を世界に合わせた表現の素材にする。

### タスクの詳細内容
・コンボの仕様
┗プレイヤーの攻撃が命中する度に数字が上がる。
　数字の表示は右詰め。

・画像別素材
┗コンボ数値のフォント
┗コンボ数値のしたの罫線
┗連撃の文字

### 期待される結果

■必要な素材
┗０～９までのフォントデータ
┗コンボ数値のしたの罫線の.png画像
┗連撃の文字のフォントデータ

以上の素材をGitHubの MS2024>２D素材＞新規フォルダ（UI）を作成＞フォルダの中に提出。

### 締め切り

11/14(木)

### 補足情報

フォントデータの用意が難しいと思うので不可能でしたらその旨伝えてもらえればIssueを閉じます。

仕様書
https://docs.google.com/spreadsheets/d/1o_tra0iHjsfij-bYmWHp4nMajjOoSt5Y/edit?gid=1714262927#gid=1714262927

現在の仮素材
![Image](https://github.com/user-attachments/assets/d3dbc8fe-cbf8-497a-8535-6d43d6dfd96a)

**Comment by okamoto0102** [comment]
タスクの詳細を記載したので、確認よろしくお願いします。

**Comment by MiyoshiTaishou** [comment]
ありがとうございます！
確認できました

**Comment by Amberi0** [comment]
０を追加と数字、文字、線のサイズ変更をしましたのでご確認お願いします。
