### ISSUE TITLE
[実装] - インターネット周りの仕様

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#332]
### タスクの目的

インターネットの同期・非同期詳細

### タスクの詳細内容

【インターネット関係参考記事】
https://www.4gamer.net/games/105/G010549/20100905002/

・同期方法について
非同期型/クライアント分散

【同期】
プレイヤーの座標
プレイヤーの当たり判定
プレイヤーが与えるダメージ
プレイヤーが受けるダメージ
プレイヤーHP（UI）
必殺技
　当たり判定
パリィ
　当たり判定
　ヒットストップ
　のけぞり
　
通常攻撃１、２、３
　攻撃の当たり判定
　敵に与えるダメージ量
かちあげ攻撃

ボスの座標
ボスの当たり判定
ボス攻撃当たり判定
ボスが与えるダメージ
ボスの受けるダメージ
ボスHP（UI等）
各ボスの攻撃判定

コンボUI
　１P２Pのコンボ数が合わさった感じ
コンボタイムリミット
　ゲージの減少
リザルト関係全般

ゲームオーバー画面
クリア画面
リザルト画面
コンフィグ

【非同期】
タイトル関係全般
接続確認画面
背景
ステージアセット
ナビゲーターUI

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
短期間で対応ありがとうございました。
ネットワークでの制作の基盤が整ってきたと思うのでこのIssueは閉じます。
問題点、改修の要望等あれば改めてIssueを出しますので対応お願いします。

**Comment by okamoto0102** [comment]
仮のタスクなので消します
