### ISSUE TITLE
[実装] - プレイヤーHP関連

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#336]
### タスクの目的

αROMに向けて必要なプレイヤーのHP関連

### タスクの詳細内容

・HPについて
　→キツネとタヌキのHPは合同（UIも）
　→プレイヤーHPの初期値＝５
・ダメージについて
　→ダメージリアクションはダメージを喰らったキャラのみ

### 期待される結果

ゲームに反映されること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

不足や疑問等あればコメントください

**Comment by okamoto0102** [comment]
会議で決まったように担当者の変更を行いました

**Comment by MiyoshiTaishou** [comment]
HPの共有と被ダメ時のアニメーション再生実装完了しました
確認お願いします。
金曜日に言うの忘れてました。
