### ISSUE TITLE
[タスク] - 水飲み鳥の攻撃のランダム化

### ISSUE THREAD

**Issue by kashitani0828** [MiyoshiTaishou/MS2024#379]
### タスクの目的

αROMに向けて水飲み鳥を完成させる

### タスクの詳細内容

・水飲み鳥の攻撃AIのランダム化をお願いします。
・詳細は仕様書に記載しています。
https://docs.google.com/spreadsheets/d/16OcVd635OmJQTnWcTnU0aXJr1V6Z9rtJ1eUeftrEnLg/edit?gid=1660777046#gid=1660777046

### 期待される結果

プログラマーが実装できること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
行動パターンランダムになるようにしました
Boss2Dに行動データリストを作成してそこに複数の行動データを入れると行動が終わるたびにランダムな行動に代わります
