### ISSUE TITLE
[タスク] - ガントチャートリスケ作業

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#429]
### タスクの目的

タスクのスケジュール期間の見直しが必要なため

### タスクの詳細内容

現状の作業の見積のし直しと
今後必要な作業を洗い出す。

### 期待される結果

プロトタイプ２～12/6まで全員の作業が
埋まっていること。

### 締め切り

10/31(木)

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
締切1日前です。

昨日メンバー全員に連絡は送ってましたが
返事が返ってきたならリスケ作業が出来ると
思いますがどうでしょうか？

まだ返事が返ってきてないのなら
催促してください。

今日は締め切りは書かなくても良いのでまず
issueを出してください。(内容は書いて)
明日で締め切りを確定させて完了です。

今日の21時にissueが上がってなさそうなら
連絡します。

**Comment by okamoto0102** [comment]
今からプランナー側のIssueを書いていきます。
それから担当プランナーが実装用のIssueを書いていきます。

**Comment by MiyoshiTaishou** [comment]
明日までにガントチャートに全員のIssueが無いと完了ではないと考えていて
担当プランナーがIssueを書くのは良いですが今日Issueを振られて明日までにそれぞれの担当者は間に合いますか？

**Comment by okamoto0102** [comment]
それは確かに厳しいと思う。
今プランナーのIssue書いてるけど
ある程度の仕様をこっちで考える必要があるから自分一人でできる限界はあると思う。

**Comment by MiyoshiTaishou** [comment]
締め切り明日なんで間に合わせないとだめなんでプランナーが考える仕様をリーダーが考える必要はないと思います。
こんな事（パリィからの連携実装とか）やりたくてそれが実現できる要素を考えて仕様書に起こしてくださいで終わると思うんでそれでプランナーに振る作業はすぐ終わると思います。

問題であるプランナーの仕様書が間に合わないに関しては仕様書が間に合ってなくてもいいので
担当者がこんな事をやってほしいをとりあえず書いてください、後は締め切り。
それ見て実装してる間に仕様書を書いてもらえればいいです。
プランナーの仕様書の締め切りを参考にプログラマーの締め切りは考えればいいと思います。

**Comment by MiyoshiTaishou** [comment]
後間に合わないのが分かっているなら早めに言ってください
こちらでも間に合わすための提案などが出来るので

**Comment by okamoto0102** [comment]
わかりました

**Comment by MiyoshiTaishou** [comment]
気になる点があるので書きます

本来は12/6までのタスクを全て振らないといけないのですがこれは無理だと思っていたのでいいのです。
ただ問題はプランナーに追加で振ったIssueがパリィからの連携攻撃だけなのがおかしいと思います。
今回の目標はα版までの仕事を振らないといけないはずです、フリーチャットに書いていた項目だと（ここから完了しているものがあるとのことなので全部ではないと思いますが）他にもやらないといけない事がたくさんあるはずです。

プランナーからプログラマーに振るのでプログラマーの部分はまだ何とも言えませんが、自分から提示できるIssueが終わったとの事なのでプランナーに振る仕事はこれで全部ということでしょうか。
エフェクトやボスの攻撃関係5つなどまだまだ振らないといけない仕事があるように見えます。

プランナーの仕事の割り振りも変でα版までにやってほしい項目よりも先にチュートリアルが書いてたりコンフィグ等α版までに必要のないものがIssueに上がっています。

纏めると
1.プランナーに振るタスクがα版までにしないといけないこと全てを満たしているように思えない
2.タスクの優先度がおかしい

**Comment by okamoto0102** [comment]
コンフィグとかそのうちいるかと思っていた仮のIssueとか残っていますね。
ややこしいと思うのでこういうのは一旦ガントチャート上から消します。

指摘通りエフェクト関連抜けているから今から出します。

**Comment by MiyoshiTaishou** [comment]
了解です
早めの対応ありがとう

**Comment by okamoto0102** [comment]
ある程度書き込みしてるものもあるので、後々必要そうなものはガントチャートの表示だけから削除します。

**Comment by MiyoshiTaishou** [comment]
issueは上げてくれてますが
プランナーとデザイナーのissueは全て上がりましたか？
まだで今日中に間に合うなら良いですが
間に合わないなら先にプランナーのissueを
あげてくださいプランナーはこのissueを
貰ってから明日の15時までにプログラマーのissueを出さないといけないので出来るだけ早めが良いです。

**Comment by MiyoshiTaishou** [comment]
了解ですじゃあ後はプランナーから
プログラマーへのissueだけって事なら
僕から進捗聞くよりもリーダーから聞いた方が
良いと思うので間に合うように進捗管理お願いします。
僕は残念ながら明日の会議参加できないので
その時に間に合ってるか分かりませんが間に合っていない場合の事も考えてせめてその日中には
間に合うようにするにはどうすれば良いかとか
考えとくとスムーズに対応できると思います。

**Comment by okamoto0102** [comment]
プランナーからプログラマーへのα版までのIssuも全部確認しました。
これ以降の動きはまだプランナー間で話あって、
ベータ版の動きを考えていきますので、別の作業を行います。

サブリーダーからも特に異論が無ければこのIssueは閉じます。
