### ISSUE TITLE
[修正依頼] - ジャンプ中の攻撃不可

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#485]
### タスクの目的

かちあげ攻撃の必要性がなくなるためジャンプ中の攻撃が出来ることを修正

### タスクの詳細内容

ジャンプ中に攻撃できないようにする

### 期待される結果

上記内容を満たしていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by Saki223** [comment]
完了。最新版で確認してください

**Comment by imasyun7** [comment]
承知いたしました。ありがとうございます。

**Comment by imasyun7** [comment]
確認しました。こちらでDoneの方に移動しておきます。
