### ISSUE TITLE
[修正依頼] - クライアント側だけ撃破時のエフェクトが表示されない

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#488]
### タスクの目的

クライアント側だけエフェクトが表示されないバグを修正

### タスクの詳細内容

クライアント側だけ撃破時のエフェクトが表示されないバグを修正

### 期待される結果

上記内容と他三つのエフェクトバグが修正されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by mathuki-takumi** [comment]
修正完了しましたので、メインへの統合作業の方よろしくお願いいたします
Boss Statusのスクリプトのほうに記述追加してあります。特にインスペクター側で設定する項目の追加などはしてないです

**Comment by mathuki-takumi** [comment]
確認作業中BossHPが０になった際、エラーが発生しパーティクルの有無が確認できなかったため現在ToDoに回しております
