### ISSUE TITLE
[修正依頼] - クライアント側だけダメージエフェクトが表示されない

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#490]
### タスクの目的

クライアント側だけエフェクトが表示されないバグを修正

### タスクの詳細内容

クライアント側だけダメージエフェクトが表示されないバグを修正

### 期待される結果

上記内容と他三つのエフェクトバグが修正されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by mathuki-takumi** [comment]
修正完了しましたので、メインへの統合作業の方よろしくお願いいたします
Boss Statusのスクリプトのほうに記述追加してあります。特にインスペクター側で設定する項目の追加などはしてないです

**Comment by okamoto0102** [comment]
ビルド通して確認できたので、完了に置いておきます！
