### ISSUE TITLE
[修正依頼] - プレイヤーが動いていないとき歩行状態になっている

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#504]
### タスクの目的

プレイヤーが動いていないときに歩行状態だと違和感があるので動いていない際はアイドル状態に修正

### タスクの詳細内容

プレイヤーを動かしていないときのアニメーションを歩行状態からアイドル状態に修正

### 期待される結果

上記内容が満たされていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by okamoto0102** [comment]
修正確認しました。
