### ISSUE TITLE
[仮素材] - タヌキ版移動アニメーション

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#518]
### タスクの目的

αROMに向けて必要なタヌキ版移動アニメーションを作成

### タスクの詳細内容

・ディスコード上にあるラフ案を参考
タヌキのカラーイラストのアニメーション素材の制作をお願いします。
・画像サイズ
ラフと同じサイズで問題ないです。
・ファイル形式: .png

### 期待される結果

アニメーションを連番ごとにファイルを分けて
githubのファイル
デザイナー＞２D素材＞playerの所に素材が入っていれば確認します。
問題点、ご相談、完了報告あればこのIssueのコメントにお願いします
締め切り
このタスクに関する締め切りがあれば記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by yomizuki43** [comment]
デザイナー＞2D素材＞player＞tanuki＞move　へ提出しました
ご確認ください

**Comment by okamoto0102** [comment]
確認にしました！
めちゃくちゃカッコイイです！ありがとうございます！

**Comment by okamoto0102** [comment]
@imasyun7 
そちらの方でも確認できたらDoneの方に移動お願いいたします

**Comment by imasyun7** [comment]
確認いたしました。ありがとうございます。
