### ISSUE TITLE
[素材] - タヌキ版かちあげのアニメーション

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#520]
### タスクの目的

αROMに向けて必要なタヌキ版かちあげのアニメーションを作成

### タスクの詳細内容

・ディスコード上にあるラフ案を参考
タヌキのカラーイラストのアニメーション素材の制作をお願いします。
・画像サイズ
ラフと同じサイズで問題ないです。
・ファイル形式: .png

### 期待される結果

アニメーションを連番ごとにファイルを分けて
githubのファイル
デザイナー＞２D素材＞playerの所に素材が入っていれば確認します。
問題点、ご相談、完了報告あればこのIssueのコメントにお願いします。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by yomizuki43** [comment]
デザイナー＞2D素材＞player＞tanuki＞give　へ提出しました
ご確認ください

【想定】
パリィ構えからの遷移

1～4f：蹴りまでの動作
※1～2f：パリィが成功したという表示
5f：蹴り
6～16f：蹴りからアイドルまでの戻り

**Comment by imasyun7** [comment]
確認いたしました。ありがとうございます。
