### ISSUE TITLE
[仮素材] - タヌキ版パリィ構えアニメーション

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#529]
### タスクの目的

αROMに向けて必要なタヌキ版パリィ構えアニメーションを作成

### タスクの詳細内容

・ディスコード上にあるラフ案を参考
タヌキのカラーイラストのアニメーション素材の制作をお願いします。
・画像サイズ
ラフと同じサイズで問題ないです。
・ファイル形式: .png

### 期待される結果

アニメーションを連番ごとにファイルを分けて
githubのファイル
デザイナー＞２D素材＞playerの所に素材が入っていれば確認します。
問題点、ご相談、完了報告あればこのIssueのコメントにお願いします。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by yomizuki43** [comment]
デザイナー＞2D素材＞player＞tanuki＞parry　へ提出しました
ご確認ください

1～5f　までが構えを想定しています

**Comment by okamoto0102** [comment]
ありがとうございます確認できました！

**Comment by yomizuki43** [comment]
申し訳ありません
一部、作画崩壊が起きていたため置き換えさせていただきました

場所：
デザイナー＞2D素材＞player＞tanuki＞parry
該当：
tanuki_parry_0002.png
