### ISSUE TITLE
[仕様書] - パリィからの連携攻撃

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#547]
### タスクの目的

パリィ成功から連携攻撃をする攻撃に細かい仕様を記載して実装担当者にIssueを出す。

### タスクの詳細内容

・連携攻撃の起動　（例）
１Pがパリィを成功させた時に敵がスタン（ダウンと違い殴り放題になるわけではない）その後にタイミングを合わせて２Pが攻撃ボタンを押したら追撃の攻撃をして敵に大ダメージを与える。

・連携攻撃の動き（例）
２Pの連携攻撃がヒットして１Pがタイミングを合わせてボタンを押したら追撃の攻撃をして大ダメージを与える。
回数制限（回数制限は調整が可能にしてもらう）
までは同じ動きを繰り返し、最後に大振りの攻撃（別モーション）をして大ダメージを与える。

・必要なエフェクト（例）
タイミングを合わせるために連携攻撃をする判定中にプレイヤーを光らせる。
連携攻撃時の別エフェクト

・敵の挙動
連携攻撃がヒットする度に短いダウンが発生

### 期待される結果

明日までに仕様を細分化してIssueの提示。プログラマーが実装に移れる状態にしてください。締め切りまでに仕様書があれば承認します。

### 締め切り

11/7までにIssueが提示。
仕様書作成：11/11（月）まで

### 補足情報

かなり遅れた動きになっているので間に合わない場合は早めに教えてください。

**Comment by okamoto0102** [comment]
溜め攻撃について記載して無かったので追記しておきます。

追記：
攻撃ボタンとは違う溜め攻撃を用意して、
それがヒットしたらパリィ成功の後の連携攻撃と一緒の動きをするように仕様を組んでください

**Comment by Saki223** [comment]
溜め攻撃の詳細は溜め攻撃のissueとしてこのissueは分けて記述してください。
