### ISSUE TITLE
[タスク] - アニメーションデータの作成

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#548]
### タスクの目的

狸のアニメーションデータを作る。

### タスクの詳細内容

狸のアニメーション素材が完成したものから。
Unityに導入して、エディタ上でアニメーションを作成する。

・作るアニメーションデータ
┗狸の待機アニメーション
┗狸の移動中のアニメーション
┗狸のジャンプ上昇中のアニメーション（ジャンプアニメーション素材を分ける）
┗狸のジャンプ下降中のアニメーション（ジャンプアニメーション素材を分ける）
┗狸のかちあげのアニメーション
┗狸のジャンプ攻撃のアニメーション
┗狸のパリィの構えのアニメーション
┗狸のパリィ成功時のアニメーション
┗狸の１撃目の攻撃アニメーション
┗狸の２撃目の攻撃アニメーション
┗狸の３撃目の攻撃アニメーション
┗狸の溜め攻撃アニメーション（攻撃のアニメーションの素材を流用）
┗ダメージリアクションのアニメーション（アニメーション素材を依頼していなかったので構えモーションで代用）
┗連携攻撃のアニメーション（攻撃アニメーションの素材を流用）
┗連携攻撃のフィニッシュのアニメーション（ジャンプ攻撃のアニメーション素材を流用）

### 期待される結果

アニメーションデータの作成と差し替えがされている。
変更がビルドシーンで確認できたら承認します。

締め切りまでにまだ上がっていない素材があると思います。
その分は他の素材で代用が聞くもので対応してください。

### 締め切り

11/13(水)

### 補足情報
https://dkrevel.com/makegame-beginner/make-2d-action-animation/

**Comment by MiyoshiTaishou** [comment]
11月14日までにこのアニメーション全部出来てるのは良いとしてもっと細分化してください
例)たぬきの攻撃関連のアニメーション11日まで

**Comment by okamoto0102** [comment]
時間かかる内容でもないし、やることも一緒なのでまとめています。
今村君が個別で指示が欲しいなら分けるけど詳細まで書くなら無駄に時間かかるのでこれでお願いしたい。

**Comment by MiyoshiTaishou** [comment]
じゃあ分けなくても良いけどどこまで出来たか
こまめに進捗聞いた方が良いよ

**Comment by MiyoshiTaishou** [comment]
アニメーションデータの作成は素材が上がるまで待ちが発生してしまうと思うので
その間にするタスクとしてボスの二体目の仕様書を作成してもらいたいのですが
他に何か優先するタスクなどあるでしょうか？

**Comment by imasyun7** [comment]
承知いたしました。二体目のボス作成しておきます。

**Comment by okamoto0102** [comment]
現状作成可能なアニメーションデータの確認できました。
残りアニメーション作成の分も別途Issue提示しますのでこのIssueは閉じます。
