### ISSUE TITLE
[実装] - パリィからの連携攻撃

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#550]
### タスクの目的

αROMに向けて必要なパリィからの連携攻撃を実装

### タスクの詳細内容
【細かい仕様書はこちら】
https://docs.google.com/spreadsheets/d/1S-3Ci8CGrg0WyjIod4XebDtHCOgO9DTaj0PzFQPEhvw/edit?gid=1120758488#gid=1120758488

・パラメータ化するもの
敵のスタン時間＝30フレーム
連携攻撃のダメージ量＝500（後で変更します）
瞬間移動時間＝60フレーム
連携攻撃回数＝３回
ノックバック距離＝１マス分

・連携攻撃
１Pまたは２Pがパリィを成功させた時に敵がスタン（ダウンと違い殴り放題になるわけではない）。
その後にタイミングを合わせて２Pまたは１Pが攻撃ボタンを押したら追撃攻撃をして大ダメージを与える。
３回まで連携攻撃を繰り返すことが可能。３回目に大振りの攻撃（別モーション）をして大ダメージを与える。
連携攻撃をしている際、ボスはノックバックする。
スタンするのは最初のパリィのみ。
連携攻撃実行中の他ボタン入力不可。

・連携攻撃の動き
２Pまたは１Pの連携攻撃がヒットして１Pまたは２Pがタイミングを合わせてボタンを押したら追撃攻撃をして大ダメージを与える。

・必要なエフェクト
パリィした後、連携攻撃がいつまで発動できるか分かりやすくするために連携攻撃するキャラの目を光らせる
例）ナルガクルガの赤い眼光のようなやつ

・敵の挙動
連携攻撃がヒットする度に短いダウンが発生

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by imasyun7** [comment]
仕様書書き終わりました。
不足等あればコメントで教えてもらえると幸いです。

**Comment by okamoto0102** [comment]
@Saki223 
明日までの実装ですが進捗いかがでしょうか？
細かい進捗状況は次の会議での報告で大丈夫です。

明日の終日まで見込み無ければ溜め攻撃の操作は確認しましたので、その分の時間を使っての実装で大丈夫ですがどうでしょうか？
この処理の後にヒットストップ作業があると思うのでそちらは別でIssueを提示いたしす！

**Comment by Saki223** [comment]
ある程度は出来てるけど細かいところの実装がまだです
なので多分間に合わない
溜め攻撃もまだ完成とは言えないと思っているが、どちらの実装を優先するかの判断をしていただきたいです

**Comment by okamoto0102** [comment]
OKです。
それでしたら、連携攻撃の作成を優先お願い致します。
ヒットストップのこと含めて今からリスケしていきます！

**Comment by Saki223** [comment]
よかです

**Comment by Saki223** [comment]
昨日会議で見せたものとほぼ変わってません
締め切りには確実に間に合わないんですけど明日やれるだけやります

**Comment by Saki223** [comment]
結構今更で申し訳ないんですが、瞬間移動時間=60フレームというのがよく分かってなくて、瞬間移動に60フレームもかけるなら30フレームしかないスタン時間に対して攻撃が間に合わなくないですか？
今はとりあえず攻撃判定が発生する瞬間にプレイヤーをボスのそばに瞬間移動させようとしてます

**Comment by imasyun7** [comment]
ご指摘ありがとうございます。確かにその通りですね。申し訳ないです。
ボスのそばに瞬間移動させようとしているとのことなので、その処理でお願いいたします。
お手数おかけしますが、よろしくお願いいたします。

**Comment by Saki223** [comment]
当日中の返信ありがとうございます。
了解です。引き続き作業を進めます。

**Comment by Saki223** [comment]
完了したので確認お願いします。以下に確認手順を記載します。

1,パリィを成立させる
2,ちょっと離れて攻撃する(ここで瞬間移動が確認できる,緑の攻撃エフェクトが出ていれば連携攻撃成功)
3,3回目の攻撃で高いダメージを与えることを確認

現状、一人でもテストしやすいようにパリィされた後の硬直を2秒にしています(変更可能)

**Comment by okamoto0102** [comment]
今村君がコントローラー壊れているので変わりに確認しました。
今のところはビルドデータでも問題なさそうだったので承認します。
