### ISSUE TITLE
[タスク] - ボスのアニメーションデータの作成

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#551]
### タスクの目的

Unityを使ってボスのアニメーションデータを作る。

### タスクの詳細内容

現状の素材を使って可能な範囲で
エディタ上でアニメーションを作成する。
素材の場所
┗Assets>Resource>Image>char>Enemy>Mizunomu
アニメーションデータの場所
┗Assets>Resource>Animation>Enemy

・現状のままで本採用するアニメーションデータ
┗ボスの攻撃（Attack）
┗ボスの歩き（Waruk１）
┗ボスのダウン（Leisure）

・作るアニメーションデータ
┗ボスのジャンプ
┗ボスのジャンプの後の攻撃
┗ボスのノックバック

### 期待される結果

アニメーションデータの作成と差し替えがされている。
変更がビルドシーンで確認できたら承認します。

### 締め切り

11/13(水)

### 補足情報
アニメーションデータを作る時の参考資料
https://dkrevel.com/makegame-beginner/make-2d-action-animation/

**Comment by MiyoshiTaishou** [comment]
前のタスクが完了しているので作業開始日を早めます。
今日から作業開始になるので作業中に変えてください。

**Comment by MiyoshiTaishou** [comment]
今確認したら待機アニメーションのSpriteのサイズが大きい状態になっていました。
修正お願いします。

**Comment by morikaito** [comment]
今日までの企画書と内定企業の提出資料の作成があるので、明日以降になりそうです。

**Comment by MiyoshiTaishou** [comment]
今日が締め切りですが進捗どうですか
吉野が担当している連携攻撃のエフェクトの問題がノックバックのアニメーションが完成すれば対応できますので
作成する三つのアニメーションデータの中でもノックバックを優先して作成して欲しいです。
出来次第プルリクエスト送ってもらえたら対応してもらうように僕の方から連絡します。

**Comment by morikaito** [comment]
15時くらいに提出できそうです

**Comment by MiyoshiTaishou** [comment]
了解しました！

**Comment by morikaito** [comment]
追加したので確認お願いします

**Comment by MiyoshiTaishou** [comment]
学校でネットワークが繋がらないので家帰ったら確認します。

**Comment by MiyoshiTaishou** [comment]
アニメーションの確認出来ました
待機のアニメーションがでかいままなのでその修正お願いします
それ以外は大丈夫そうでした

**Comment by MiyoshiTaishou** [comment]
待機のアニメーションとりあえずサイズが合うようにこっちで変更しました
