### ISSUE TITLE
[仕様変更] - １ボスの仕様変更

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#552]
### タスクの目的

ボスの仕様変更で必要箇所を相談して、Issueを書く

### タスクの詳細内容

ボスの行動パターンをリーダーと相談して見直す。
変更が必要な分のIssueを出す。

### 期待される結果

11/7(木)中にIssueを出す。
仕様書作成を11/11(月)まで作成

### 締め切り

11/11(月)

**Comment by okamoto0102** [comment]
追加のエフェクトのIssu
┗衝撃波
┗予備動作

**Comment by kashitani0828** [comment]
![ノックバック](https://github.com/user-attachments/assets/91c417bc-4c60-4370-b779-259dde458b26)

**Comment by okamoto0102** [comment]
Issueと仕様書変更箇所の確認できましたので閉じておきます
