### ISSUE TITLE
[実装] - 溜めている時のエフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#563]
### タスクの目的

プレイヤーが溜め攻撃をするまで、
力を溜めていることがわかるエフェクト出せるようにする。

### タスクの詳細内容

溜めている時間の調整は溜め攻撃の方で調整をするので、それに合わせてエフェクトが出るようにしてください。

■エディタで変更できる箇所
┗溜めている間のエフェクトーエフェクトのプレハブ

### 期待される結果

ビルドシーンで確認してクライアント側でも問題なく仮のエフェクトが表示されていれば承認します。

### 締め切り

ガントチャートで調整します。

### 補足情報

溜め攻撃の実装や仕様がまだなので変更点があれば追記します。

**Comment by aoi0708** [comment]
澤野の溜め攻撃が終わるまでどう頑張っても達成できないのでスケジュールの見直しをお願いします

**Comment by okamoto0102** [comment]
了解です！対応します。

**Comment by okamoto0102** [comment]
3撃目のエフェクトのエフェクトの修正依頼を出しているのでそちらの対応を先にお願いします。
その間にパリィの連携攻撃ができたらそのエフェクトの実装
＝＞溜め攻撃のエフェクトのスケジュールに変更しました。
これで動けるでしょうか？

**Comment by aoi0708** [comment]
大丈夫です
対応ありがとうございます

**Comment by okamoto0102** [comment]
調整箇所と実装の確認できました。
Doneに移動しておきます。
