### ISSUE TITLE
[実装] - 連携攻撃のエフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#564]
### タスクの目的

連携攻撃のエフェクトを出せるようにする。

### タスクの詳細内容

■連携攻撃の説明
溜め攻撃かパリィの後にもう片方のプレイヤーが追撃してダメージを与える攻撃です。

■エディタで変更できるようにする箇所。
┗追撃攻撃エフェクトーエフェクトのプレハブ

### 期待される結果

ビルドシーンで確認してクライアント側でも問題なく仮のエフェクトが表示されていれば承認します。

### 締め切り

ガントチャートで調整します。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by aoi0708** [comment]
確認お願いします。
