### ISSUE TITLE
[エディタ] - ボスの追加の行動パターンの作成

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#565]
### タスクの目的

エディタで調整できる範囲でボスの行動パターンを増やす。

### タスクの詳細内容

・追加の行動パターン２つ
通常攻撃のスピードを変更した攻撃
２連撃→３連撃にして増やす。

### 期待される結果

ボスのAIまでデータを作成して、作ったデータを報告してください。
報告を貰ってビルドシーンのデータに差し替えをして問題なければ承認します。

### 締め切り

ガントチャートで調整します。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
Uploading MS2025 2024-11-07 14-50-53.mp4…

**Comment by MiyoshiTaishou** [comment]
既に1ボスの仕様書が完了しているようなので作業開始日を早めます
今日から作業開始になるので作業中に変えてください。

**Comment by MiyoshiTaishou** [comment]
今日が締め切りですが進捗どうですか
間に合わなさそうなら報告お願いします

**Comment by kashitani0828** [comment]
作成できたのですが、データの送り方がわからないので教えていただきたいです。

**Comment by MiyoshiTaishou** [comment]
データをボス2dにあるボスAIコンポーネントに
ボスの行動データを入れる箇所があります。
そこに入れればその中からランダムでsequenceが選ばれます
HP50％以降の行動はその設定項目の下にあると思うのでそこに同じように入れてもらえれば
動きます
自分が作ったsequenceがちゃんと動くかどうかはの確認は行動データを一つにすれば確認しやすいと思います

**Comment by kashitani0828** [comment]
そこまで完成してるのですが、プルリク送ればいいのでしょうか？そうなのであればやり方分からないので教えてください。

**Comment by MiyoshiTaishou** [comment]
プルリクはGitHub desktopから行います。
![image](https://github.com/user-attachments/assets/d79abe7f-79b9-4b3a-a068-612c0a1dac83)

この画像の左に変更箇所が表示されて
問題なければ左下に実装内容を書いて
左の一番下にあるcommitを押してください

そこまで出来たら右に青いボタンでクリエイト
プルリクエストがあると思うのでそこをクリックするとサイトに飛びます後は表示されている
青いボタンを押していけば送れると思います

**Comment by MiyoshiTaishou** [comment]
やり方書きましたがどうですかプルリクエスト出来そうですか
澤野の方でマニュアルをDiscordにあげているのでそちらの方を見た方がわかりやすいかもしれないです
コンフリクトやその他Gitで問題が起きた場合は報告してもらえたら対応します。

**Comment by kashitani0828** [comment]
お手数お掛けしてすみません。わかりやすい説明ありがとうございます。プルリク遅れたと思うので確認お願いします。

**Comment by okamoto0102** [comment]
@MiyoshiTaishou 
コンフリクト起きているみたいです。
申し訳ないですが対応お願いできますか？

**Comment by MiyoshiTaishou** [comment]
対応しました

**Comment by okamoto0102** [comment]
コンフリクト対応ありがとうございます！
一旦このデータ取り込んでビルドデータ作成します。

**Comment by MiyoshiTaishou** [comment]
確認した結果問題なさそうであれば報告ください
今日が一日タスクフリーなので問題が無ければチュートリアルの仕様書の開始日を早めるか
問題があれば今日までに対応してもらってください
