### ISSUE TITLE
[実装] - 溜め攻撃のエフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#566]
### タスクの目的

溜め攻撃の斬撃エフェクトを出せるようにする。

### タスクの詳細内容

溜め攻撃の斬撃エフェクトを個別で出したいので
エディタで変更できるようにしてください。

### 期待される結果

ビルドシーンで確認してクライアント側でも問題なく仮のエフェクトが表示されていれば承認します。

### 締め切り

ガントチャートで調整します。

### 補足情報

溜め攻撃の実装や仕様がまだなので変更点があれば追記します。

**Comment by aoi0708** [comment]
確認お願いします。

**Comment by okamoto0102** [comment]
調整箇所と実装の確認できました。
Doneに移動しておきます。
