### ISSUE TITLE
[仕様変更] - ２連撃の仕様変更

### ISSUE THREAD

**Issue by kashitani0828** [MiyoshiTaishou/MS2024#567]
### タスクの目的

α版に向けて、２連撃を完成させる

### タスクの詳細内容

２連撃の仕様変更（2回ともパリィできるようにする）
・１撃目はパリィされてもノックバックしない処理
・２撃目がパリィされた時にノックバックする処理
・１撃目がパリィされてももう一度攻撃を続行する処理
上記３つの処理の作成をお願いします

仕様書は適宜更新していくのでこちらから確認お願いします。
https://docs.google.com/spreadsheets/d/16OcVd635OmJQTnWcTnU0aXJr1V6Z9rtJ1eUeftrEnLg/edit?gid=324806611#gid=324806611

### 期待される結果

仕様書通りになっており、上記３つの処理が完成し、プランナーが調整できること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

フレームはプランナーで調整できるようにお願いします。

**Comment by kashitani0828** [comment]
![ノックバック](https://github.com/user-attachments/assets/68315e4d-d9b9-4e12-9f9c-54038bd07f04)
参考動画です

**Comment by MiyoshiTaishou** [comment]
ボスの攻撃データにノックバックするかどうかの項目を追加しましたtrueの場合はノックバックします
ボスの行動データを一撃目はfalse二撃目はtrueにしたらやりたい事が出来ると思います。
確認お願いします。
