### ISSUE TITLE
[修正依頼] - ３撃目のエフェクトの修正

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#569]
### タスクの目的

3撃目のエフェクトの問題を解決する。

### タスクの詳細内容

3撃目のエフェクトが１撃目、2撃目でも再生されているためその問題を解決して欲しいです。

### 期待される結果

問題解決がビルドデータを通して確認できたら承認します。

### 締め切り

ガントチャートで調整します。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
https://github.com/user-attachments/assets/f5ebcf34-421e-42d9-89b6-a2a90cf48cb6

**Comment by aoi0708** [comment]
修正したので確認お願いします。

**Comment by okamoto0102** [comment]
対応遅れて申し訳ありません
確認します。

**Comment by okamoto0102** [comment]
早期の対応ありがとうございます！確認できましたので、Doneに移動しておきます。
