### ISSUE TITLE
[実装] - 溜め攻撃

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#570]
### タスクの目的

αROMに向けて必要な溜め攻撃を実装

### タスクの詳細内容

【細かい仕様書はこちら】
https://docs.google.com/spreadsheets/d/1S-3Ci8CGrg0WyjIod4XebDtHCOgO9DTaj0PzFQPEhvw/edit?gid=1897154837#gid=1897154837

・パラメータ化するもの
敵のスタン時間＝30フレーム
溜め攻撃＝180フレーム
溜め攻撃のダメージ量＝500（後で変更します）
瞬間移動時間＝60フレーム
追撃攻撃のダメージ量＝300（後で変更します）
連携攻撃回数＝３回
ノックバック距離＝１マス分

・溜め攻撃
１Pまたは２Pが敵に溜め攻撃を当てると敵がスタン（ダウンと違い殴り放題になるわけではない）。
その後にタイミングを合わせて２Pまたは１Pが攻撃ボタンを押したら追撃攻撃をして敵に大ダメージを与える。
３回まで連携攻撃を繰り返すことが可能。３回目に大振りの攻撃（別モーション）をして大ダメージを与える。
スタンするのは最初の溜め攻撃のみ。
溜め攻撃中の移動は不可。

・溜め攻撃の動き
２Pまたは１Pの溜め攻撃がヒットして１Pまたは２Pがタイミングを合わせてボタンを押したら追撃攻撃をして大ダメージを与える。

・必要なエフェクト
溜め攻撃した後、追撃攻撃がいつまで発動できるか分かりやすくするために追撃攻撃するキャラの目を光らせる
例）ナルガクルガの赤い眼光のようなやつ

・敵の挙動
溜め攻撃がヒットする度に短いダウンが発生

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by imasyun7** [comment]
仕様書書き終わりました。
不足等あればコメントで教えてもらえると幸いです。

**Comment by Saki223** [comment]
さっき口頭で伝えられた要素をここに残しときます
・溜め行動中は移動できない

質問
溜め行動からは溜めきって攻撃する以外に、攻撃やパリィで溜め行動をキャンセル出来たりしますか？

**Comment by Saki223** [comment]
了解です

**Comment by okamoto0102** [comment]
連携攻撃の完成に集中して頂くので、このIssueはβ版作業に以降します。

**Comment by aoi0708** [comment]
澤野からこのissueを貰います

**Comment by okamoto0102** [comment]
了解です！
担当の変更をしておきました。

**Comment by okamoto0102** [comment]
お疲れ様です！
今日までの締め切りとなっておりますが進捗いかがでしょうか？
明日からマージ作業になると思いますので、そちらと上手い具合に時間決めて作業しているとかでしたらその旨の報告をお願いします！

**Comment by aoi0708** [comment]
ナルガクルガみたいな感じで目を光らせるエフェクトはとりあえずαまでは絶対無理なので別でissueを立てて私に割り振っておいて欲しいです。

他の部分は澤野に処理の確認などもしながらになるので出来れば今週の木曜日までは時間が欲しいです。

**Comment by aoi0708** [comment]
エフェクトに関してはそれで合ってます

あと仕様書での質問なんですが溜め攻撃でのノックバックとはボスがするという認識で合ってますか？

**Comment by imasyun7** [comment]
ノックバックの件ですが、ボスがノックバックするという認識で大丈夫です。
お手数おかけしますが、引き続き作業のほうよろしくお願いいたします。

**Comment by aoi0708** [comment]
返信ありがとうございます
ボスがノックバックする場合ボス担当に別でissueを立てた方がいいかもしれないです

**Comment by imasyun7** [comment]
承知いたしました。後程、ボス担当者にノックバックのIssueを提示しておきます。

**Comment by MiyoshiTaishou** [comment]
ノックバック作成しましたIssueは大丈夫です

**Comment by aoi0708** [comment]
確認お願いします。

**Comment by aoi0708** [comment]
溜め攻撃は最大まで溜まったら自動で攻撃する感じであってますか？

**Comment by imasyun7** [comment]
申し訳ないです、記載していなかったです。
最大まで溜まったらボタンを離して発動する処理をお願いいたします。
一応、最大まで溜まったらプレイヤーの周りをエフェクトを纏わせて分かりやすくしたいと思っています。
別途、エフェクトのIsuueを出したいと思います。
お手数おかけしますが、よろしくお願いいたします。
