### ISSUE TITLE
[仕様変更] - 衝撃波の仕様変更

### ISSUE THREAD

**Issue by kashitani0828** [MiyoshiTaishou/MS2024#571]
### タスクの目的

α版に向けて、衝撃波の攻撃を完成させる

### タスクの詳細内容

衝撃波の攻撃をパリィできないようにする処理をお願いします

仕様書は適宜更新していくのでこちらから確認お願いします
https://docs.google.com/spreadsheets/d/16OcVd635OmJQTnWcTnU0aXJr1V6Z9rtJ1eUeftrEnLg/edit?gid=324806611#gid=324806611

### 期待される結果

仕様書通りになっており、上記の処理が完成し、プランナーが調整できること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

フレームはプランナーも調整できるようお願いします

**Comment by MiyoshiTaishou** [comment]
ボスの攻撃データにパリィ可能かどうかの判定を入れましたパリィ出来ない攻撃はチェック外せばパリィしてもダメージくらいます。
確認お願いします。
