### ISSUE TITLE
[実装] - 衝撃波のエフェクト 

### ISSUE THREAD

**Issue by kashitani0828** [MiyoshiTaishou/MS2024#573]
### タスクの目的

α版に向けて、衝撃波攻撃にエフェクトがでる処理をお願いします。

### タスクの詳細内容

ボスの足から中心になるようにエフェクトが出るような処理をお願いします。
参考資料です
![750320031 335464](https://github.com/user-attachments/assets/a52ecc44-5519-4c35-bed4-b87e6511d736)

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

エフェクトのタイミングはinspectorviewでプランナーが調整できるようにお願いします。

**Comment by okamoto0102** [comment]
最新のROMのビルドシーンがエラーがでていて確認できなかったです。
対応が終わったら確認します。

**Comment by MiyoshiTaishou** [comment]
締め切り二日前です
明日の会議参加できなかったと思うのでここに進捗と間に合うかどうか書いておいてください

**Comment by okamoto0102** [comment]
金曜日に直接報告を受けております。
今から他のIssuと一緒にチェックします。

**Comment by MiyoshiTaishou** [comment]
完了していて後はチェック待ちって事ですか？
後Issueです定期的にIssuになってますよ

**Comment by okamoto0102** [comment]
金曜日終わりがけでしたので、その時はエラーで確認できませんでした。
誤字の指摘いつもすみません極力気をつけます！

**Comment by okamoto0102** [comment]
@Suika225 
すみません。金曜日承った報告のものが最新版で確認できなかったので、
どこを確認して欲しいのか、コメントで教えてください。

**Comment by Suika225** [comment]
Resource/ShockwaveにあるShockwaveプレハブまたは、ダメージテストシーンに仮設置してあるのでご確認ください

**Comment by MiyoshiTaishou** [comment]
確認は出来ましたか
問題がある場合は報告を問題が無い場合は完了にしてください

**Comment by okamoto0102** [comment]
了解です！
今日中に確認します。

**Comment by MiyoshiTaishou** [comment]
僕今確認出来ないので何とも言えないですが
コメントの内容的にボスの攻撃のタイミングで
エフェクトが出るが出来てなさそうに思いました

ボスの攻撃に合わせて出るまでで完了ですが
間に合いそうでしょうか？

**Comment by okamoto0102** [comment]
確認しました！
Shockwaveプレハブの動きが確認できなかったので、
ダメージテストシーンの方で確認しようと思いましたが、
そちらの方ではエラーが起きたので確認できませんでした。

**Comment by okamoto0102** [comment]
![スクリーンショット 2024-11-12 194948](https://github.com/user-attachments/assets/918a205e-ae03-454d-85f3-b930619c75a0)

**Comment by okamoto0102** [comment]
・上のエラー
Problem detected while opening the Scene file: 'Assets/Scenes/hirai/DamageTest.unity'.
Check the following logs for more details.

・下のエラー
Prefab instance problem. Missing Prefab Asset: 'Shockwave (Missing Prefab with guid: 0f5d5a83c685931428e660589c978251)'

**Comment by MiyoshiTaishou** [comment]
平井君今日バイトがあるか分かりますか？

**Comment by okamoto0102** [comment]
@MiyoshiTaishou 
バイトかどうかは聞いてないですね・・・

**Comment by okamoto0102** [comment]
どの道エラーの対応と
指摘にあったコメントの内容的にボスの攻撃のタイミングで
エフェクトが出る処理らしきものは確認できなかったので、
このIssueは閉じるしかないかもしれないです…

**Comment by MiyoshiTaishou** [comment]
閉じる事は出来ないんですよ。
issueに書いている事が実装出来ていないのに
閉じたら出来てないけど終わったことになって
この問題が放置されたまま次のタスクする事になってしまうでしょ

**Comment by okamoto0102** [comment]
思いつく対象方としては、
松木君の攻撃エフェクトの処理が上手く使い回せないかですかね。

松木君にも確認しないといけないし、実際この問題をどうするかは平井君に聞かないとわからないです。

**Comment by MiyoshiTaishou** [comment]
ちゃんと締め切りに間に合わす為にまずは
担当者にLINEかディスコで連絡とってください
連絡が取れない場合は間に合わす為に僕が家帰ったらとりあえずエラーの項目確認します

**Comment by okamoto0102** [comment]
とりあえず平井君には連絡送りました。
エラー項目の確認よろしくお願いします！
作り直しをしないいけないとかでしたら先ほど言った対象方を取った方が確実だと思いますがいかがでしょうか？

**Comment by MiyoshiTaishou** [comment]
僕が今日見て直せそうなら終わらせます。
後21時までに反応無かったら電話してください

僕もエフェクトに関しては今回実装してないのでネットワーク対応部分で不安があります。
申し訳ないですが松木君がこの時間フリーなら
見てもらいたいですね。

**Comment by okamoto0102** [comment]
わかりました。対応ありがとうございます。

**Comment by okamoto0102** [comment]
今平井君と一緒に作業して、
エラーの解消確認できました！
ただ、ボスの攻撃のタイミングでエフェクトが出る処理は未実装で、本人もやり方分からなかったと報告もらいました。

そこは仕方ないので、また別途自分からIssueを提示してβ版の初めの内に取り掛かって頂くことで話をさせて頂きました。
理由としては、平井君にお願いするようなβ版作業まではまだ洗出ししていないのと
松木君のβ版作業でお願いしたいことは、別であったためです！

**Comment by MiyoshiTaishou** [comment]
実装方法が分からないなら相談をしてください
チームなんで勿論協力しますし1人で悩まずに
相談してください。
誰に相談すれば良いか分からないなら
とりあえず僕に言ってもらえたら僕の方で解決出来そうな人探しますんで。
締め切りギリギリになってから言われると
求められているタスクの実装が間に合わなくなります。
こまめな報連相お願いします。

**Comment by MiyoshiTaishou** [comment]
実装依頼を出した人が確認遅れれば遅れるほど
問題の発見が遅れて夜中に対応しないといけない事になります。
今回の担当者は梶谷君だと思うのでなるべく
早く確認するようにお願いします。
課題や他のタスクで忙しい場合は他の人に
頼むなどして締切に間に合うように余裕を持った確認お願いします。

**Comment by MiyoshiTaishou** [comment]
仕方ないって事はないんですよ
タスクの管理者がこまめに確認して明らかに
確認が遅れている、間に合うか怪しいとかは
分かります。
今回僕も気付くのに遅れて17時の段階でやっと気付きました
こういう確認漏れが無いように僕も朝10時ぐらいに一回全部のタスク確認だけじゃなくて
昼と夜にも確認をしていきます。

**Comment by okamoto0102** [comment]
このまま期限を伸ばすのもややこしいので別でIssueを提示しました。
そちらの方で作業の報告をよろしくお願いいたします。

このIssueは一旦閉じます。
