### ISSUE TITLE
[タスク] - ベータ版に向けた作業の洗出し

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#575]
### タスクの目的

ベータ版の作業を洗出し、プランナーへの指示をだしてベータ版までのガントチャートを作成する。

### タスクの詳細内容

■リーダーの出すIssue
┗プランナーへの指示のIssue
┗自分が担当になる箇所のIssue
┗その他必要な提出物の作業があれば
┗スケジュール確認用の仮のタスク

### 期待される結果

仮のタスクを含めて12/6(金)までの動きをガントチャートに入れる。

### 締め切り

11/15(金)

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
作業開始日が過ぎています
作業中に入っていないので入れてください

**Comment by MiyoshiTaishou** [comment]
了解です。

**Comment by MiyoshiTaishou** [comment]
締め切り二日前です進捗どうですか

・ダブルパリィ仕様
・壁、床、橋、柵のIssue

・ステージの配置
・スコアの仕様

・必殺技の演出の作り直し
・エフェクトの差し替え

・狸の残りのアニメーション
・狐のアニメーション
・ボス２のデザイン
・壁、床、橋、柵　ステージ周り

・ボス３
・リザルトのUI

どこまでがリーダーが作成するIssueか分かりませんが
この辺りが作成するIssueなのかなと思いました。
12個のIssueを二日でやらないといけなさそうですが間に合いますか？
間に合わなさそうなら他のプランナーと協力などして分担してください

**Comment by MiyoshiTaishou** [comment]
森君のタスクが今無いのでIssueの優先度はまず森君にしてもらう作業のIssueから上げた方が良いと思います

**Comment by okamoto0102** [comment]
今からIssueの打ち込みしていきます。

**Comment by okamoto0102** [comment]
２０時まで全て打ち込み終わらないと思うので、一旦提示するIssueを記載しておきます。
〇の印のものは記載済み。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
■プランナー
・ボス３の内容を決める＜＝11/14(木曜日)に会議

・ボス２仕様　担当者：今村

・ダブルパリィ仕様：今村

・ステージの配置：森〇
・スコアの仕様：森〇

・必殺技の演出の作り直し
・UI配置
・残り必要エフェクトの洗出し
・エフェクトの差し替え

２ボスの行動データ作成：今村
２ボスのアニメーションデータ作成：今村

３ボスの行動データ作成：樫谷
３ボスのアニメーションデータ作成：樫谷



■プログラマー
・１ボス　衝撃波エフェクトの実装：平井〇
・HPバーの処理の修正依頼：松木
・連携攻撃時に目を光らせるエフェクト：吉野〇

・ボス２
・ダブルパリィ

・スコアのシステム
・チュートリアルシステムの完成

・ボス３



■デザイナー
・狸の残りのアニメーション〇
・狐のアニメーション＜＝Issueは出し終わっている〇
・ボス２のデザイン
・ボス２のアニメーション
・壁、床、柵　のモデル＜＝スケジュール変更
・リザルトのUI


・ボス３の
・リザルトのUI

**Comment by MiyoshiTaishou** [comment]
井上さんのタスクが全て完了したのでこちらのIssueも優先してあげてください

**Comment by MiyoshiTaishou** [comment]
プログラマーのIssueが12月6日まで振られていませんがこれはプランナー側で振るから問題ないのであればこのIssueは完了にしますが
その認識で間違いないですか

**Comment by okamoto0102** [comment]
その認識で問題無いです!
