### ISSUE TITLE
[修正依頼] - ボタン配置変更

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#580]
### タスクの目的

ユーザーが分かりやすくするためにボタン配置の調整を行います

### タスクの詳細内容

Bボタン　攻撃
　→よく使う通常攻撃を押しやすいBに配置
Aボタン　ジャンプ
RB　パリィ
　→右によく使用するボタンがあるのでRBを使用
Yボタン　溜め攻撃
　→攻撃の択を瞬時に対応できるように攻撃ボタンの近くに設置
Bボタン＋RB　必殺技
　→よく戦闘で使うボタンを使用することでユーザーが対応しやすくなる

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

ボタン配置の意見などあればコメントで教えて下さい
分からないところ不足等あればコメントで教えてください

**Comment by Saki223** [comment]
対応しました。確認お願いします

**Comment by imasyun7** [comment]
承知いたしました。プルリク出してから確認いたしますので少々お待ちください。

**Comment by okamoto0102** [comment]
今日確認する作業が複数あるので、そちらとまとめて今日中に確認します。

**Comment by imasyun7** [comment]
こちらの不具合で必殺技以外確認できました。ありがとうございます。
不具合対応中なので、今日中には確認いたします。
