### ISSUE TITLE
[実装]-リザルト画面配置(レイアウト)

### ISSUE THREAD

**Issue by morikaito** [MiyoshiTaishou/MS2024#583]
**タスクの目的**
リザルト画面の素材の配置

**タスクの詳細内容**
リザルトの配置をお願いします。
プレイヤーのキャラクターによってリザルト画面が変更するようにしてください。
メインゲームから取得してくる情報は下記です。
・最大コンボ数
・クリアタイム
・ジャンプ攻撃回数

画像で使用する素材は、
unity内の、Resouce>Image>UI>Result に入っています

下記はイメージ画像です。
![Image](https://github.com/user-attachments/assets/d982740f-bf3b-49a2-9e3b-07db4c416b3c)
![Image](https://github.com/user-attachments/assets/19b271bd-5996-47b3-99d8-e2715c10ba1d)

**期待される結果**
このタスクが完了した際に得られる結果や、完了の基準を記載してください。

**締め切り**
締め切りはリーダーからの指示に従ってください。

**補足情報**

**Comment by MiyoshiTaishou** [comment]
赤い巻物がありませんでしたとりあえず緑を先実装するので素材を入れておいて欲しいです。

**Comment by MiyoshiTaishou** [comment]
実装に必要な項目
シーンをまたいでも共有しないといけないデータ
クリア時間、コンボ数、連撃数

**Comment by MiyoshiTaishou** [comment]
レイアウトの配置ほぼ完了しました。
フォントの関係で使えない漢字があったりしたのでそこだけ変えたりしないといけないです

プレイヤーのキャラクターによってリザルト画面が変更するようにしてください。
メインゲームから取得してくる情報は下記です。
・最大コンボ数
・クリアタイム
・ジャンプ攻撃回数

ここら辺はリザルト画面のシステムになってくると思うのでそちらの締め切りに合わせて実装しようと思っています。

ResultScene_Miyoshiで配置確認できます。
確認お願いします。

**Comment by okamoto0102** [comment]
@morikaito 
レイアウトの確認できました。
そちらでも確認できましたらDoneに移動をお願い致します。

**Comment by morikaito** [comment]
unity内の、Resouce>Image>UI>Result に「makimonoRed」を追加しています。導入お願いします

**Comment by Saki223** [comment]
「ジャンプ攻撃回数」としてカウントする条件は、
1,かちあげジャンプ攻撃がヒットした時
2,空中の敵に対してかちあげジャンプ攻撃がヒットした時(ボスがダウン状態になる)

のどちらかだと考えていますが、どの条件の時にカウントしますか？

**Comment by morikaito** [comment]
「ジャンプ攻撃回数」としてカウントするのは、
1,かちあげジャンプ攻撃がヒットした時のカウントをしてください。
よろしくお願いします

**Comment by Saki223** [comment]
了解です
