### ISSUE TITLE
[タスク] - α版用ビルドデータ作成

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#600]
### タスクの目的

α版の発表に必要なビルドデータの作成

### タスクの詳細内容

タイトルからゲームシーン、リザルトまでのゲームループが出来る状態のビルドを完成

### 期待される結果

11/13にマージ作業が完了して14日までにビルドデータが完成している事

### 締め切り

11/14

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
ビルドデータ提出完了したので閉じます。
