### ISSUE TITLE
[タスク] - α版発表用資料作成

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#608]
### タスクの目的

α発表会で使う為の資料の作成

### タスクの詳細内容

発表に必要な物をパワポなどで製作する
内容は製作者が考える

### 期待される結果

締切日に必要な資料が完成している事

### 締め切り

11/14

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始です作業中の所に入れておいてください
ただタスクが今二重になってしまっているのでどちらも締め切り通りに間に合うなら良いですが
間に合わない場合はこの発表用資料作成が他のメンバーに代わりに振れるなら担当者を変えるなどして
二つのタスクが完了できるように対応してください。

**Comment by okamoto0102** [comment]
優先順位付けて取り掛かっていくので、
今日はまだこっちには取りかからないと思います。
ただし、前の資料の使いまわしをしてブラッシュアップしていくので、期限には間に合うと思います。
また、実作業に取り掛かる時に作業中の方に移しておきます。

[01_発表資料.pdf](https://github.com/user-attachments/files/17694972/01_.pdf)

**Comment by MiyoshiTaishou** [comment]
締め切り1日前です進捗どうですか
使いまわしをブラッシュアップするとのことなので期限には間に合うと思いますが
厳しそうなら他のプランナーと協力して分担してください

**Comment by okamoto0102** [comment]
![Image](https://github.com/user-attachments/assets/226c191b-2b32-49b2-aa95-6bc3a93ef6e4)
![Image](https://github.com/user-attachments/assets/1f08f339-976d-4efe-a2d6-6b009d051876)
![Image](https://github.com/user-attachments/assets/43742463-77c6-4b13-80e4-66afb5d8f728)
![Image](https://github.com/user-attachments/assets/8b0284b9-a72c-40ac-9a9f-f3d28fa1e418)
![Image](https://github.com/user-attachments/assets/f9ff1a3b-927e-4d26-b965-7a00fc5b470e)
![Image](https://github.com/user-attachments/assets/bcdfc0bc-b33e-4220-86fd-c7ac6276e928)

一旦途中経過あげておきます。

**Comment by MiyoshiTaishou** [comment]
β版への動きでボス3やステージの作成などが書いてませんがここの完成に向けては
ざっくりとした内容だけ書く感じにしてるんでしょうか？

**Comment by okamoto0102** [comment]
提出物まとめました
