### ISSUE TITLE
[タスク] - 狸の待機アニメーションの作成

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#616]
### タスクの目的

狸の待機アニメーションの作成

### タスクの詳細内容

Unityで待機アニメーションデータの作成

### 期待される結果

アニメーションデータの作成が完了している状態

### 締め切り

11/12

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by imasyun7** [comment]
対応いたしました。確認お願いいたします。

**Comment by MiyoshiTaishou** [comment]
ありがとうございます
確認ですがこの後出かけないといけないので遅くなります
会議までには確認します

**Comment by okamoto0102** [comment]
ありがとうございます。
今日確認する作業が複数あるので、他のIssueもそちらとまとめて今日中に確認します。

**Comment by imasyun7** [comment]
プルリクが反映されていませんでした。今送りましたので、アニメーション確認できる状態だと思います。

**Comment by MiyoshiTaishou** [comment]
ありがとうございます！
確認できました。
