### ISSUE TITLE
[タスク] - 狸の歩行アニメーション作成

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#617]
タスクの目的
狸の歩行アニメーションの作成

タスクの詳細内容
Unityで歩行アニメーションデータの作成

期待される結果
アニメーションデータの作成が完了している状態

締め切り
11/14

補足情報
タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by imasyun7** [comment]
対応いたしました。確認お願いいたします。
