### ISSUE TITLE
[修正依頼] - 連携攻撃のエフェクトの問題

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#619]
### タスクの目的

連携攻撃のエフェクトが通常攻撃にも発生していたので、対応お願いします。

### タスクの詳細内容

連携攻撃のエフェクトが通常攻撃の時に発生しないように変更をお願いします。

### 期待される結果

連携攻撃の完成時に連携攻撃のエフェクトが出ている

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

実装の確認は連携攻撃の完成時に同時に確認します。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業中の所に入れてください

**Comment by Saki223** [comment]
連携攻撃かどうかを判断するアルゴリズム上、のけぞり中以外にも連携攻撃扱いになるタイミングが発生しています。
原因としてはのけぞり中専用のアニメーションがないことなので、のけぞりアニメーションが実装され次第改善できると思います。

**Comment by MiyoshiTaishou** [comment]
のけぞりのアニメーションデータが実装されたと思うので修正対応お願いします。

**Comment by MiyoshiTaishou** [comment]
修正対応間に合いましたか
報告お願いします

**Comment by aoi0708** [comment]
エフェクトの問題は治ってますがパリィした後にカウンターまで自動で発動するままになっているのでそれを澤野が直すことになると思います

**Comment by aoi0708** [comment]
確認お願いします。

**Comment by okamoto0102** [comment]
授業中に相談した内容でまたIssueの提示をします

**Comment by okamoto0102** [comment]
こっちのIssueは問題ありませんでした承認します。
