### ISSUE TITLE
[実装]-通常攻撃

### ISSUE THREAD

**Issue by morikaito** [MiyoshiTaishou/MS2024#62]
**タスク目標**
通常攻撃の実装

**タスク詳細**
・攻撃は3連撃になっており、1撃ごとの間に攻撃ボタンを押すことによってコンボがつながるように設定
・ボタンを連打をしていてもコンボがつながるよう設定
・各攻撃の発生時にプレイヤー前方に当たり判定を出現
・1撃目は1P,2撃目は2P,3撃目は両プレイヤーで攻撃するため、各攻撃終了後にどちらが攻撃できるのかの判定も実装
※当たり判定の出現フレーム数や範囲を変更できるような形で実装してください

**タスク締め切り**
※未定(リーダー等と話し合って決めていきます)

**備考**
詳細な仕様は後ほど仕様書として提出するので、確認お願いします。
提出時に通知をします。

**Comment by okamoto0102** [comment]
1撃目を2P、2撃目を1Pでも攻撃出来るってイメージであっていますか?
