### ISSUE TITLE
[実装] - 溜め攻撃のヒットストップ

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#624]
### タスクの目的

溜め攻撃のヒット時に発生するヒットストップの作成

### タスクの詳細内容

■実装内容
・停止対象は自身のみ
・停止時間の調整方法はInspecterViewにて個別に設定
・停止時間の単位はf(60/sec)

### 期待される結果

調整する為のスクリプトと項目を報告お願い致します。
ビルドシーンのビルドデータで確認できたら承認します。

### 締め切り

ガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Saki223** [comment]
完了しました。
ヒットストップ時間の調整はPlayerの子オブジェクト「ChargeAttackArea」のChargeAttackAreaDamageのStopFrameで調整できます。
現在はわかりやすくするために大げさに停止時間を長くしています

確認お願いします

**Comment by okamoto0102** [comment]
確認しました。ありがとうございます！
