### ISSUE TITLE
[タスク] - 狸の攻撃アニメーション一撃目作成

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#635]
### タスクの目的

狸のアニメーション作成

### タスクの詳細内容

攻撃のアニメーションを実装する

### 期待される結果

狸のアニメーションが期日までに完成し
ゲーム画面で見れる事

### 締め切り

11／13

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by imasyun7** [comment]
対応いたしました。確認お願いいたします。
二連撃と三連撃の方も一撃目のアニメーションに書き換えました。
後、既存のエフェクトと被ってしまっているので、削除のほうお願いいたします。

**Comment by MiyoshiTaishou** [comment]
ありがとうございます！
確認できました
エフェクトに関しては僕の方から連絡しておきます。
エフェクトの削除が完了するまでは閉じないようにしますが
タスクとしてはもう完了しているのでまたボス二体目の仕様書の作業お願いします。

**Comment by imasyun7** [comment]
エフェクトの件、承知いたしました。ありがとうございます。

**Comment by aoi0708** [comment]
エフェクトを消しておきました

**Comment by imasyun7** [comment]
承知いたしました。対応ありがとうございます。

**Comment by okamoto0102** [comment]
ありがとうございます！
アニメーション確認できました。
