### ISSUE TITLE
[実装] - 追撃の時のエフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#639]
### タスクの目的

溜め攻撃した後、追撃攻撃がいつまで発動できるか分かりやすくするために追撃攻撃するキャラの目を光らせる
例）ナルガクルガの赤い眼光のようなやつ

### タスクの詳細内容

追撃可能時間に合わせてエフェクトの発生時間を調整できるようにしてください。

### 期待される結果

エフェクトの発生時にボタン入力をして追撃が発生していることが確認できたら承認します。

### 締め切り

11/18(月)途中経過～11/21（木）に修正依頼含めて完成報告

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by aoi0708** [comment]
軌跡みたいなのを出すことはできたのですがキャラクターの目の位置を取れないので目からナルガクルガみたいな軌跡を出すのは厳しいです

**Comment by okamoto0102** [comment]
位置の調整をプランナー側でできるようにするのは可能でしょうか？

**Comment by aoi0708** [comment]
Assets/Resource/Effectの中にあるTrajectoryというprefabを付ければTrajectoryの中心から軌跡は出るようになります

**Comment by okamoto0102** [comment]
承知致しました。エフェクトの発生は確認できました！
授業で相談した内容で改めてIssueを提示します
