### ISSUE TITLE
[仕様書] - ダブルパリィの仕様書

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#650]
### タスクの目的

ダブルパリィの仕様書を作成して、Issueの提示をお願いします。

### タスクの詳細内容

■ダブルパリィのイメージ
ボスがダブルパリィでしかはじくことができない攻撃をしてくるからそれをプレイヤー2人で息を合わせてダブルパリィする。

■考えて欲しい細かい仕様
・ダブルパリィの判定の取り方
・ダブルパリィが発生した事がわかる演出
・ダブルパリィ後のボスの反応

### 期待される結果

Issueの提示が確認できたら承認します。

### 締め切り

他のタスクを提示した後にガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Saki223** [comment]
提案です。
プレイヤー二人ともがパリィを成立させないとパリィできないボスの攻撃や、タヌキしかパリィできない攻撃、キツネしかパリィできない攻撃とかもあると面白そうだと思いました。

**Comment by imasyun7** [comment]
提案ありがとうございます。
『プレイヤー二人ともがパリィを成立させないとパリィできないボスの攻撃』は、ボス２で実装予定です！
『タヌキしかパリィできない攻撃、キツネしかパリィできない攻撃』は、ボス２の仕様にそれっぽいものがあるので案を踏まえて落とし込めるか検討してみたいと思います。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください

**Comment by MiyoshiTaishou** [comment]
締め切り二日前です進捗どうですか
報告お願いします

**Comment by imasyun7** [comment]
仕様書が５割程度で終わっている状態です。
テストプレイまで作業できるので、その時間で終わらせようと思います。
