### ISSUE TITLE
[素材] - タイトルUI

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#654]
### タスクの目的

このタスクの目的を簡潔に説明してください。

### タスクの詳細内容

タスクで行う具体的な作業内容を記載してください。

### 期待される結果

このタスクが完了した際に得られる結果や、完了の基準を記載してください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Amberi0** [comment]
タスクの詳細が欲しいです。
タイトルUIの素材は
「ゲーム開始」「コンフィグ」「終了」のUIだけでよろしいのでしょうか？
![Image](https://github.com/user-attachments/assets/442f2bb5-85a9-415d-9e2d-53d2de9a84dc)

**Comment by okamoto0102** [comment]
すみません。
先に仕様の方に取り掛かっていまして、まだ必要UIを全部は出せていません。11/21までには全部終わります。
ゲーム開始/コンフィグ/終了はありますので、そちらを先に取り掛かって頂けると助かります！

**Comment by Amberi0** [comment]
承知いたしました。
先にそちらのUIを取り掛かります。追加で質問なのですが
「ゲーム開始」→「入室」or「開始」
「コンフィグ」→「部屋を探す」に変更してもよろしいでしょうか？

**Comment by okamoto0102** [comment]
提案ありがとうございます！「ゲーム開始」はその変更でOKです！
「コンフィグ」は音量の設定とかをする画面の方なので「設定」とかでどうでしょうか？

**Comment by Amberi0** [comment]
なるほど！入室設定ボタンだと思ってました！「設定」で作ってみようと思います！

**Comment by Amberi0** [comment]
イメージ
![Image](https://github.com/user-attachments/assets/5151b305-7ef8-4cf5-9f95-65f5ce6d170c)

**Comment by okamoto0102** [comment]
https://docs.google.com/spreadsheets/d/1JWiZGrvxsdbx0w0WYcbzJLnbYy_HjY_w/edit?usp=sharing&ouid=116919724162584186530&rtpof=true&sd=true

仕様書記載致しました。

一応、演出イメージもこちらで作ってみましたがこの様なイメージでよろしいでしょうか？
https://github.com/user-attachments/assets/03605338-03e9-44ec-bafd-441669f15c8e

**Comment by Amberi0** [comment]
・「始める」「戻る」UI
・部屋選択の枠縁
・松竹梅の選択UI
を追加しました。
枠縁の画像サイズはパソコンの画面サイズと同じ
松竹梅UIをピッタリ配置して欲しいです。

**Comment by Suika225** [comment]
部屋選択の枠縁に説明用のテキストが乗ったままになっているので削除したデータをあげてほしいです

**Comment by Amberi0** [comment]
部屋選択の枠縁説明用テキストがを削除したものを追加しました。
