### ISSUE TITLE
[仕様書] - チュートリアルの仕様書

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#658]
### タスクの目的

チュートリアルの仕様書を修正して、Issueの提示をする

### タスクの詳細内容

チュートリアルの仕様書で変更のある場所の記載と
Issueの提示をお願いします。

■実装されている内容
メンバー全員が指定のエリアに揃ったら画面遷移処理
（人数はインスペクターで変更可能デバック時に一人でもできるようにするため）

チュートリアルボスの行動変化をプレイヤー側で行えるようにした
チュートリアル用のボスの行動データ（待機だけと待機と攻撃の繰り返し）

現在はすぐにボス戦行けた方がデバック便利だと思うので僕のタイトルシーンでのみチュートリアルシーンに行けるようにされている。

### 期待される結果

Issueの提示とプログラマーが実装に取り掛かっている事が確認できたら承認します。

### 締め切り

ガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業開始したら作業中に変えてください

**Comment by MiyoshiTaishou** [comment]
大体締め切りの真ん中ぐらいですが進捗どうですか
報告お願いします

**Comment by kashitani0828** [comment]
仕様書、Issue共に完成しました。

**Comment by okamoto0102** [comment]
Isuueの提示と仕様書確認しました！ありがとうございます！
三好君が今他に優先する作業あるので、他にタスクに空きができそうな方に僕の方で割り当てます！
