### ISSUE TITLE
[仮タスク] - 狸の残りのアニメーション

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#677]
### タスクの目的

狸の残りのアニメーションデータを作成する。

### タスクの詳細内容

狸のアニメーションでまだ作成されていないアニメーションを作ってください。

### 期待される結果

狐のアニメーション作業もあるので、この仮タスク期間内には狸のアニメーションが
ゲームで動いているようにしてください。

### 締め切り

ガントチャートで調整

### 補足情報

こちらは仮タスクなので仕上がったアニメーションから別でIssueを提示します。

**Comment by imasyun7** [comment]
パリィアニメーションデータ作成しましたが、コントローラーが壊れたせいで確認できません。
時間空いている人いましたら、確認作業をよろしくお願いしたいです。

**Comment by okamoto0102** [comment]
こっちの作業ひと段落したら確認しておきます。
