### ISSUE TITLE
[タスク] - リザルトの演出の相談

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#680]
### タスクの目的

担当プログラマーと話し合ってどういう演出を作るのか考えてください。

### タスクの詳細内容

11/15にリザルトシーンでどういう演出を作れるのかを相談して、
Issueを提示してください。

### 期待される結果

Issueの提示が確認できたら承認します。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
出来ること
TimeLineを利用したSEやアニメーション（αの調整や座標回転など）制御など
Maskをしてキャラのカットインのような演出なんかは作れると思います。
ただセンスは無いので画面の具体的なイメージ図が欲しいです
細かい部分の調整などもそちらでやってもらいたいです

**Comment by MiyoshiTaishou** [comment]
巻物ー＞狸（右から左）ー＞文字関係ぽんぽんぽんー＞スコアばん！
最後にメニュー関係のUI出す。

イメージ図は貰う

**Comment by morikaito** [comment]
パワポ等でイメージアニメーションを作成完了しだい、タスク完了にします。

**Comment by MiyoshiTaishou** [comment]
締め切りを再調整したいのですがどれぐらいで出来ますか

**Comment by okamoto0102** [comment]
リザルトUI素材の完了を確認しましたので、
その分の期限を使ってイメージアニメーションの作成をお願いします！

**Comment by MiyoshiTaishou** [comment]
UnityにUI素材入れました
井上さんのイメージ図の感じで配置またしときます
明日のバイト帰ったらやるんで遅くなると思います

**Comment by MiyoshiTaishou** [comment]
締め切り一日前ですが進捗どうですか
報告お願いします

**Comment by morikaito** [comment]
![Image](https://github.com/user-attachments/assets/fb451a1d-d373-45ed-880b-95335fea17ec)
こんな感じで考えてます
