### ISSUE TITLE
[仕様書] - タイトルの仕様書

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#693]
### タスクの目的

タイトルの仕様書を作成する。

### タスクの詳細内容

タイトルの仕様を考えて実装担当者にIssueを提示

メモ
部屋決めてるのを松・竹・梅みたいな感じで部屋を選べる感じにしたい

### 期待される結果

仕様書の作成とIssueの提示をしたら承認

### 締め切り

ガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください

**Comment by MiyoshiTaishou** [comment]
締め切り二日前です
進捗報告お願いします

**Comment by okamoto0102** [comment]
現在口頭ベースで担当者には動いて貰っている状態です。
今日中にはIssueの詳細化と今補足資料を作っています。
UIの方も同時並行中です！

**Comment by okamoto0102** [comment]
https://docs.google.com/spreadsheets/d/1JWiZGrvxsdbx0w0WYcbzJLnbYy_HjY_w/edit?usp=sharing&ouid=116919724162584186530&rtpof=true&sd=true

仕様書の方書き終わりました。
UIの分も書き終わりましたので、Issue出しておきます。
