### ISSUE TITLE
[仕様書] - タイトルのUI

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#694]
### タスクの目的

タイトルの画面の必要なUIを考えて担当者に依頼をする。

### タスクの詳細内容

タイトルの仕様書でレイアウトを考えます。
そのレイアウトに合わせて必要な素材の依頼をしてください。

### 期待される結果

担当者にIssueの提示が確認できたら承認します。

### 締め切り

ガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください
