### ISSUE TITLE
[タスク] - インストラクションカード

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#697]
### タスクの目的

インストラクションカードを作成する。

### タスクの詳細内容

■インストラクションカードの概要
◆インストラクションカードの制作（担当：井上）
　インストラクションカードとは、ゲームの遊び方を事前に把握できるようなもの

　役割：待ち時間の間に遊び方を理解させる

　設置方法
　・掲示
　　→A1パネルの右横が良さげ
　・カードとして渡し見ていただく

◆ハレパネという粘着付きのパネルがあるのでカラーコピーを貼って使用すると良い

　【必要な事項】
　　1.キャラクター操作方法
　　2.画面写真2～3点
　　3.ゲームの目的
　　（何々を目指せ！的なもの）
　　4.ゲームのロゴ
　　5.ビジュアルの統一

◆すぐ後ろともうひとつ後ろの人に見えるぐらいのサイズ（文字などはっきりと）

〆切：１２月４日
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
■やること
説明文・スクリーンショットを共有するので、
それを引継ぎレイアウトを作成する。

### 期待される結果

インストラクションカードの完成

### 締め切り

１２月４日

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
進捗状況
![Image](https://github.com/user-attachments/assets/de723ba1-24f5-4cff-b1e5-a86b556ece20)

**Comment by okamoto0102** [comment]
説明資料と一緒にこちらも引き継いで貰う事になりました。ので
森君に担当者を変更します。

**Comment by morikaito** [comment]
編集したものです
https://109.gigafile.nu/0316-c0c5d9c2fd813d80cc52220713f21938b
