### ISSUE TITLE
[修正依頼] - ボスのHPのUIシステム

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#706]
### タスクの目的

ボスのHP処理を想定の仕様書で作り直しをお願いします。

### タスクの詳細内容

・ボスのHPバーを複数本表示できるようにしてください。
・今まで通り与えたダメージを表示してください。
・ボスのHPバー1本に付き、どれ位のHPなのか調整を可能にしてください。

参考画像

https://github.com/user-attachments/assets/ee605acd-32e9-4526-86d5-8475cce422ed

### 期待される結果

調整をするためのオブジェクトとスクリプトを報告してください。
ビルドシーンで確認できたら承認します。

### 締め切り

ガントチャートで調整

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください

**Comment by MiyoshiTaishou** [comment]
締め切り二日前です進捗どうですか

**Comment by mathuki-takumi** [comment]
HPBarが順に消えるよう調整しましたので確認お願いします

**Comment by okamoto0102** [comment]
ありがとうございます!
確認ます!

**Comment by okamoto0102** [comment]
返信遅くなり申し訳ありません。
クライアント側だけ、バーが消えていなかったのです。
ネットワーク関係のものだと思うので月曜日中までに対応よろしくお願いします！

https://github.com/user-attachments/assets/bf97414d-dbea-4a85-a5c2-a2657863421d
