### ISSUE TITLE
[仮タスク] - タイトルの画面のシステム実装

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#715]
### タスクの目的

タイトル画面でマッチングと部屋の選択ができるようにしてください。

### タスクの詳細内容

・テキストの入力場所を消してください。
・部屋を入る場所をコントローラー入力で選択できるようにする。　松・竹・梅
・マッチング画面に移動してホスト側が狸、クライアント側を狐で表示する。
・ボタン入力で準備OKをして2人プレイヤーがそろえばシーン遷移

タイトル画面の仕様書
┗https://docs.google.com/spreadsheets/d/1JWiZGrvxsdbx0w0WYcbzJLnbYy_HjY_w/edit?usp=sharing&ouid=116919724162584186530&rtpof=true&sd=true

※現在仕様書は制作中です。更新をかけた場合随時通知致します。

### 期待される結果

仮タスクなので小分けして、別途Issueを提示します。

### 締め切り

ガントチャートで調整

### 補足情報

こちらは仮タスクです。
仕様書作成段階で詳細については多少変更があることはご了承ください。
仕様書担当：岡本

**Comment by Suika225** [comment]
画像無しで実装可能な範囲での実装が完了しました　タイトルシーンで確認できます
