### ISSUE TITLE
[実装] - ロケットパンチ

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#729]
### タスクの目的

βROMに向けて必要なボス２のロケットパンチを実装

### タスクの詳細内容

【細かい仕様書はこちら】
https://docs.google.com/spreadsheets/d/1KGKzqeqihs0LoMw7aG-i5Vhx68p0KoYs9U-rULMvo24/edit?gid=1660777046#gid=1660777046

・パラメータ化するもの
敵とプレイヤーの距離＝８マス

・ロケットパンチ
プレイヤーから敵が一定距離、離れている場合ロケットパンチの処理を行う

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by MiyoshiTaishou** [comment]
締め切りを提示して欲しいです
今の僕のタスクはリザルトの演出面をやるタスクがあるのですが優先度としてはボスの方が高そうな気がするのでそのあたりを森君と
相談して欲しいです。
僕のざっくり見積もりだと攻撃の判定が移動する処理で二日かかると思います。

**Comment by MiyoshiTaishou** [comment]
距離で行動が変わるというのがどういった処理になるかで実装までの時間がかなり変わってきます。

実装が早い方法
ボスの行動は今まで通り上から順番に流して攻撃のタイミングで離れているか？フェイントにするかなど判定を取ってその時に変える

メリット：実装が早い、今まで通りのボスの行動調整が出来るのでバランス調整がおそらく簡単
デメリット：ボスの行動にアドリブが聞かないので行動が少なすぎると単調に見えてしまう（増やせばある程度カバー可能だと思う）

実装に時間がかかる方法
ボスの行動表とは別で独自の判定を作り条件を満たした場合は今の行動をキャンセルして即座にそのアクションを行う

メリット：ボスの行動が設定した行動から急に別のアクションに行くためプレイヤーの動きに応じて動くためより考えて行動しているように見える、今後の事を見据えてより複雑な条件にも対応できる設計にすればプレイヤーの状態に合わせて行動を柔軟に変えれるようになる

デメリット：設定項目が増えるのと条件を満たしたらその行動にすると無限に同じ行動になる可能性もある（ここは確率で行うとかにしたら解決）実装に時間がかかる上のやり方なら2,3日でいけそうだがこっちが5日ぐらい欲しい

**Comment by MiyoshiTaishou** [comment]
当たり判定をプレイヤーに向かって飛ばす処理を実装しました
TutorialMoveAttackで設定をいじれます基本は鳥の攻撃と変わりませんが違う点が攻撃の移動にかける時間とアニメーションカーブです
アニメーションカーブをいじると徐々に早くなる攻撃や最初が早くてそのあとゆっくりになるなど攻撃の速度にバリエーションを付けれます
僕のTitleSceneからチュートリアルシーンに飛べてそこで確認できます

**Comment by imasyun7** [comment]
お疲れ様です。返信遅くなり申し訳ありません。
実装までの時間の件、承知いたしました。
自分の返答が遅れたせいで今どちらの方向で進んでいるか分かりませんので、今進めている方法で大丈夫です。
当たり判定をプレイヤーに向かって飛ばす処理ありがとうございます。
確認なのですが、プレイヤーと敵の距離が何マスでこの処理は行われますか？
お手数おかけしますが、ご返答のほどよろしくお願いいたします。

**Comment by MiyoshiTaishou** [comment]
プレイヤーと敵の距離が何マス離れてたらの所が
実装方法によって期間が変わる部分で今は条件式は無しでとりあえずロケットパンチの動きの部分だけ実装しました。

個人的にやりやすい方法はこのロケットパンチをするタイミングで距離を計算して遠かったら
ロケットパンチ、近かったら何か別の行動みたいに出来るのが一番やりやすくて早いです。

後遠距離攻撃がメインの敵ならプレイヤーから離れれような動きが必要かなと思ってます
ボスの仕様がどうなるかわからないですが
ステップ回避のような素早く短距離を移動する物が必要そうなら実装します

**Comment by imasyun7** [comment]
お疲れ様です。返信遅くなり申し訳ありません。
ご提案ありがとうございます。確かに、遠距離攻撃が主体のキャラクターなので、プレイヤーから離れるステップのような動きが必要ですね。
ステップの仕様を書き込んで、また後程Issueで出しておきます。
すみません、工数が増えてしまいますがよろしくお願いいたします。

**Comment by MiyoshiTaishou** [comment]
近かったら通常行動離れたらロケットパンチをするようにしました。
ステップの動きはノックバックアクションを行動表に組み込めばプレイヤーから離れるように動きます値がでかすぎると瞬間移動みたいになるので25当たりで調整するのが良いと思います。
