### ISSUE TITLE
[素材]-リザルトUI

### ISSUE THREAD

**Issue by morikaito** [MiyoshiTaishou/MS2024#733]
**タスクの目的**
リザルトで必要なUI素材の作成

**タスクの詳細内容**
リザルトで必要な素材
・巻物(緑・赤　計2色)
　┗リザルトの文字などの背景として使います。
・選択ボタン(計3種)
　┗「メニュー」「もう一度」「次へ」の文字をお願いします。
　┗和風テイストなフォントで制作してください。
・選択中がわかるUI
　┗選択ボタンの中でどれを選択しているのかを可視化するためのUI
　┗ボタンの背景に墨の横線を入れる感じのものを制作してください。
・スコアハンコ(各スコア3種　カラー2種(赤・緑)　計6種)
　┗「S」「A」「B」のスコアを獲得した時のハンコを作成してください
　┗現在仮のUIを使っているので、その雰囲気を維持した状態のUIを作成してください。
　┗このゲームならではの物などを入れてくれると嬉しいです。

**期待される結果**
各UIの作成完了

**締め切り**
ガントチャーで決められた日時を締め切りとします。

**補足情報**
スコアハンコは、リザルト画面の手形の部分に置く形になります。
現在のROMで使用している仮のUIレイアウト等を下に貼っておきます。

![Image](https://github.com/user-attachments/assets/435bea60-3824-4bf9-b097-e6378f416689)
![Image](https://github.com/user-attachments/assets/49c0a543-45d4-4dd5-bc2e-e00395b53660)
![Image](https://github.com/user-attachments/assets/0ca53a72-2108-4242-99d1-2c9c7cccaf6c)

**Comment by Amberi0** [comment]
現在、テストで作っていただいてるリザルトには「ジャンプ攻撃」の代わりに「れんけいすう」が入っていますが「ジャンプ攻撃」に変更でよろしいでしょうか？

依頼：リザルトの全体完成図をディスコードにも上げている下の画像のように配置にしてほしいです。![Image](https://github.com/user-attachments/assets/35d2e7d9-84b4-4cb6-a602-ce1d86a6860b)
![Image](https://github.com/user-attachments/assets/b1f27bf7-a599-4b28-9639-a59ccb1da1ca)

**Comment by MiyoshiTaishou** [comment]
配置は僕が担当しているのでその配置通りに作ります

**Comment by morikaito** [comment]
現在、ジャンプ攻撃回数をカウントするようにプログラムしてくれていると思うので、「ジャンプ攻撃」での制作をお願いします。

**Comment by morikaito** [comment]
井上さんが制作してくれていた画像に、スコアのハンコ的なものを表示したいと思うのですが、手形の部分に入れる感じでもいいでしょうか？

**Comment by Amberi0** [comment]
ジャンプ攻撃に差し替えた素材を追加させていただきました。命名：result_UI2
肉球ハンコのところにはスコアを入れて欲しいです。
ハンコデザインも作ってみたのですが、他リザルトUIと同じ作りでカラフルにした物の方が映えていて見やすいと思うので変更したいです。赤緑統一だと単調に見えると思うので

![Image](https://github.com/user-attachments/assets/4cc9b3a6-3955-4ad4-a975-b92fc18096f6)
![Image](https://github.com/user-attachments/assets/e63a81f9-fa8b-4b15-a936-3d7112aed8cc)
![Image](https://github.com/user-attachments/assets/afaacb50-aa87-4d9e-a0d0-3a4d4e12820e)

**Comment by Amberi0** [comment]
リザルトUI更新しましたのでご確認お願いします。
![Image](https://github.com/user-attachments/assets/21bd3e81-0878-4141-b7dc-1bd9efcadff1)
![Image](https://github.com/user-attachments/assets/5a006d73-e123-4135-974d-1529be9dfe24)
