### ISSUE TITLE
[タスク] - カメラのズーム処理

### ISSUE THREAD

**Issue by MiyoshiTaishou** [MiyoshiTaishou/MS2024#740]
### タスクの目的

プレイヤーの距離に応じてかめらの距離が変わる仕組みの実装

### タスクの詳細内容

スマブラのようなカメラワークの処理を実装
設定できる項目
カメラのズームの倍率（プランナー側で適切な距離を調整してもらうため）

### 期待される結果

プレイヤーが離れたり近づいたりしたらカメラがズームアウトする

### 締め切り

11/20

### 補足情報

18日から始めると思うのでそこから一日ごとにここまで出来たら終わるであろうスケジュールを記載します

18日：カメラのズームアウト処理（インスペクターで数値を変えたらズームアウト出来る）
19日：プレイヤーの距離に応じて値が変わる処理（ここで取得した値を上のインスペクターで変えた値にすれば動く）
20日：レビューを貰って問題点があれば対応（ここは余裕をもっての日数なので問題が無ければ次のIssueへ）

タスクに空きがあったので実装がいるであろう物を僕の方で作りました何か問題があれば連絡ください

**Comment by Saki223** [comment]
でけた
わーいわーい

**Comment by MiyoshiTaishou** [comment]
今日の自習時間に確認して問題なければ閉じます
