### ISSUE TITLE
[実装]-リザルトの演出

### ISSUE THREAD

**Issue by morikaito** [MiyoshiTaishou/MS2024#756]
**タスクの目的**
リザルト演出(アニメーション等)の実装

**タスクの詳細内容**
リザルト画面時のアニメーションを実装してください。
1,襖が閉まる
2,巻物が左上から流れてくる
3,たぬきが出現(プレイヤーが狐の場合は、狐)
4,評価項目表示
5,評価項目の結果を表示
6,スコアを表示(スタンプを押す感じのアニメーション)
7,メニューなどの選択項目表示
8,選択しているものの場所に線を表示

期待される結果
リザルト演出(アニメーション等)の実装の完了

締め切り
リーダ等が提示したガントチャートを参照

補足情報

**Comment by morikaito** [comment]
イメージアニメーションです。

![Image](https://github.com/user-attachments/assets/46a14780-3dad-4f8b-9db9-4ce805c3d078)

**Comment by Suika225** [comment]
リザルトのメニューどれが選択されてるかわかりずらくなってますがどうします？
