### ISSUE TITLE
[修正依頼] - 連携攻撃のエフェクト

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#760]
### タスクの目的

連携攻撃ができるタイミング中に
ボタン入力ができることがわかるエフェクトの実装

### タスクの詳細内容

連携攻撃ができるタイミング中に
小川さんがあげている[!]の2Dスプライトを表示してください

### 期待される結果

スプライトの位置調整が可能なことと
ビルド通して問題なければ承認します。

### 締め切り

12/22(金)

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください

**Comment by aoi0708** [comment]
今上がっている素材ですが「！」までプレイヤーのアニメーションと一緒に上がっているので、スプライトの位置調整が可能なこととというのが実現出来ないです。

**Comment by imasyun7** [comment]
小川さんに修正依頼のIssue出しました。
後程、別で素材が出てくると思うので対応お願いいたします。

**Comment by aoi0708** [comment]
ボスがのけぞっている間は「!」を表示するところまではできましたが、プレイヤーの行動後の硬直の間は出ないようにする処理が今の状態だと作るのが難しいので、澤野に投げた硬直のissueが終わるまでは完成させるのが難しいです。

**Comment by okamoto0102** [comment]
了解しました！
表示されているのは確認しましたので、澤野に投げたIssueが終わった時に改めて対応お願いします！

**Comment by aoi0708** [comment]
確認お願いします

**Comment by okamoto0102** [comment]
エディタの状況が変わっていたので、今日上げてあったビルドデータで確認しました。
表示の方は問題なさそうなので、承認しておきます！
