### ISSUE TITLE
[修正依頼] - 『！』マークとタヌキかちあげアニメーションを別に

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#767]
### タスクの目的

タヌキのかちあげアニメーションに入っている『！』マークとアニメーションを別にする

### タスクの詳細内容

エフェクトに使用するために『！』マークとかちあげアニメーションを別にする

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by yomizuki43** [comment]
すみません...issueの方、今気づきました。
現状報告です。

朝にリーダーからの連絡に気づき、ディスコードの［制作物・ラフなど］チャンネルに！マークフキダシを置きました。
（提出先が不明だったのでディスコードに置きました）

タヌキかちあげアニメーションに関して、
リーダーから修正しなくて大丈夫とのことだったので、何も変更を加えてないです。

確認と他要望（フォルダの方に入れてほしい、タヌキかちあげからフキダシを外してほしい　など）あれば連絡ください

**Comment by aoi0708** [comment]
！をディスコから拾いましたが大丈夫そうだったのでプログラマーはそちらで作業します。
ありがとうございます。
その他のことについてはプランナーに確認お願いします。

**Comment by okamoto0102** [comment]
ありがとうございます！
ディスコードで確認していますのでこちらで閉じておきます！
