### ISSUE TITLE
[修正依頼] - プレイヤーの行動の硬直をまとめる

### ISSUE THREAD

**Issue by aoi0708** [MiyoshiTaishou/MS2024#781]
### タスクの目的

硬直がそれぞれの行動のスクリプトで分けて管理していると硬直時に連携攻撃可能かどうかの「!」を出さないようにする処理が作れないため

### タスクの詳細内容

今はそれぞれの行動のスクリプトで硬直を決めていますが硬直用のスクリプトを作ってすべての行動の硬直をそのスクリプトで管理してほしい

### 期待される結果

硬直の処理がまとめられている

### 締め切り

11/21(木)

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by Saki223** [comment]
でけた
わーいわーい
