### ISSUE TITLE
[実装] - タイトルの画面の演出

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#793]
### タスクの目的

タイトルの画面の演出を作る。

### タスクの詳細内容
▼演出イメージ
https://github.com/user-attachments/assets/8849ab6a-6d31-4e29-b874-51ab993270a4

### 期待される結果

イメージ通りの演出を作ってください。

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

コンフィグ画面にも同じように使い回しがきく用にしておきたいです。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業中に変えてください
タイトル画面のシステムは画像ない範囲で出来ているみたいなので
こちらもアニメーションだけ先に作成して素材上がり次第差し替えの形で動いてほしいです

**Comment by okamoto0102** [comment]
@Suika225 
本日作業締め切りになっています！
進捗報告お願いします！

**Comment by okamoto0102** [comment]
返信がないのでDMで確認取ります

**Comment by Suika225** [comment]
演出イメージのようなアニメーションの実装が完了しました

**Comment by okamoto0102** [comment]
昨日の作業時間でタイトル画面の作業の報告承りました！
ありがとうございます！

演出方針の変更点については改めてIssueを提示しますのでそちらで確認よろしくお願いします！
