### ISSUE TITLE
[実装] - コンフィグ画面実装

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#812]
### タスクの目的

タイトルのコンフィグ画面で音の設定をできるようにする。

### タスクの詳細内容
仕様概要
![スライド3](https://github.com/user-attachments/assets/9e75c32a-b1a3-4181-9692-0a453bff9edd)

### 期待される結果

上記内容を実装確認をビルドデータで確認できたら承認します。

### 補足情報

タスク実行に際しての注意点や追加の情報があれば記載してください。

**Comment by okamoto0102** [comment]
@aoi0708 
会議で言っていたIssueの提示しておきました！
一旦期限ガントチャートで引いておりますが、何かあれば言ってください！
調整します。

**Comment by MiyoshiTaishou** [comment]
今日から作業開始です作業中に変えてください

**Comment by okamoto0102** [comment]
@aoi0708 
昨日の会議で共有して貰った実装状況を基に仕様書に変更を加えました！確認よろしくお願いします！
仕様書
https://docs.google.com/spreadsheets/d/1JWiZGrvxsdbx0w0WYcbzJLnbYy_HjY_w/edit?usp=sharing&ouid=116919724162584186530&rtpof=true&sd=true

![Image](https://github.com/user-attachments/assets/c2f39654-41bf-4a5b-b807-e408168233ed)

**Comment by okamoto0102** [comment]
選択用のに使ったアイコンの素材を共有しておきます。
基の素材に縁取りがなくてみずらかったので縁取りをパワポで付けた方の画像も上げておきます！
サイズが異なるかもしれません申し訳ない。

![Image](https://github.com/user-attachments/assets/70804990-acd3-4e90-bcec-a32767498cfd)

![Image](https://github.com/user-attachments/assets/cdcfb381-8f23-44ea-808b-07a62d08b95e)

**Comment by okamoto0102** [comment]
コンフィグ用の丸ぽち頼まれていたので貼っておきます
![Image](https://github.com/user-attachments/assets/1c0d97a5-314e-409b-91e1-7fea83ee4758)
![Image](https://github.com/user-attachments/assets/be945e57-b78e-4e96-9faa-2fe607328179)

**Comment by okamoto0102** [comment]
![Image](https://github.com/user-attachments/assets/0a7a6746-f17e-45b8-b146-4daf811ec97c)

**Comment by okamoto0102** [comment]
![Image](https://github.com/user-attachments/assets/87f97511-73d0-43ca-8156-499aa65617cb)
