### ISSUE TITLE
[実装] - ダブルパリィ

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#832]
### タスクの目的

βROMに向けて必要なプレイヤーのダブルパリィを実装

### タスクの詳細内容

【細かい仕様書はこちら】
https://docs.google.com/spreadsheets/d/1S-3Ci8CGrg0WyjIod4XebDtHCOgO9DTaj0PzFQPEhvw/edit?gid=629672527#gid=629672527

・パラメータ化するもの
パリィ時発動猶予＝2フレーム
パリィ判定＝直径３マス
ヒットストップ＝３フレーム
ボスノックバック距離＝４マス

・ダブルパリィ
二人のプレイヤーがRボタン同時に押すとこの処理を行う

・判定処理
プレイヤーのパリィ処理と同じ
但し、Rボタンを同時に押さないと発動しない

・エフェクト

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by Saki223** [comment]
完了しました。
検証手順は以下↓

①MargeSceneに配置されているBoss2Dの子オブジェクトのBossAttackAreaにアタッチされているBossAttackAreaのTypeをALLからDOUBLEに変更
②エディタで実行して一人ではパリィが成立しないことを確認
③エディタとビルドデータで実行、ビルドデータ側の画面を選択すると二人同時に動かせるので攻撃をパリィする
結果：ボスがのけぞり状態になったらＯＫ

**Comment by imasyun7** [comment]
検証したので、Mergedに移動します
