### ISSUE TITLE
[実装] - 連携アニメーション

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#833]
### タスクの目的

βROMに向けて必要な連携アニメーションを実装

### タスクの詳細内容

連携アニメーションの素材が来るまで、仮で通常攻撃アニメーションを使いまわして実装する

Resource＞Animation＞Playerに入っているAPlayerCoordinated Attackを使用してください

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by MiyoshiTaishou** [comment]
今日から作業開始なので作業始めたら作業中に変えてください。

**Comment by okamoto0102** [comment]
@imasyun7 
確認よろしくお願いします！

**Comment by imasyun7** [comment]
コントローラーがないため明日確認します
