### ISSUE TITLE
[素材] - ロケットパンチアニメーション

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#836]
### タスクの目的

βROMに向けて必要なボス２のロケットパンチアニメーションを作成

### タスクの詳細内容

【細かい仕様はこちら】
https://docs.google.com/spreadsheets/d/1KGKzqeqihs0LoMw7aG-i5Vhx68p0KoYs9U-rULMvo24/edit?gid=182028344#gid=182028344

・ロケットパンチアニメーション
火が何も点火していない状態と徐々に火が点火していくアニメーションを作成

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by Amberi0** [comment]
ロケットパンチ（両手）素材追加しました。
身体はでき次第上げます。
箸を持っている右手が余裕があればブラッシュアップします。
