### ISSUE TITLE
[修正依頼] - コンボUI

### ISSUE THREAD

**Issue by imasyun7** [MiyoshiTaishou/MS2024#842]
### タスクの目的

必殺技の発動が分かりやすいようにコンボが溜まったらコンボUIを赤くする

### タスクの詳細内容

【細かい仕様はこちら】
https://docs.google.com/spreadsheets/d/1o_tra0iHjsfij-bYmWHp4nMajjOoSt5Y/edit?gid=1714262927#gid=1714262927

・コンボUI
必殺技は発動できるコンボ数溜まったら、コンボUIの色を赤くする
必殺技を発動したタイミングで色を黒に戻す

### 期待される結果

上記内容が実装されていること

### 締め切り

このタスクに関する締め切りがあれば記載してください。

### 補足情報

分からないところ不足等あればコメントで教えてください

**Comment by aoi0708** [comment]
![Image](https://github.com/user-attachments/assets/38c24c9d-2c8a-40da-97a9-045450fad5b0)

specialColorの色を変えればコンボUIの色がその色に変わります

**Comment by okamoto0102** [comment]
![Image](https://github.com/user-attachments/assets/a799c691-c5e5-433e-9663-b93f92cbee13)

必殺技可能になった時の演出のイメージこんな感じです！
以前お伝えしたように意図としては、必殺技の発動にコンボが条件になっていることやプレイヤー2人にあからさまな変化がでるようにしてわかりやすくする意図があります！

**Comment by okamoto0102** [comment]
プレイヤーのところの炎は３Dのエフェクトが丁度良さそうなものがあったのでこちらでお願いします。
https://assetstore.unity.com/packages/vfx/particles/fire-explosions/procedural-fire-141496

**Comment by okamoto0102** [comment]
必殺技発動処理に変更を加えるのでログとして残しておきます。
①RB+Bで数秒間必殺技待機状態(仮)に移行、エフェクトの色が変わる。
②必殺技待機状態の時は動けない。
③必殺技待機状態の相方がいる場合にRB+Bで必殺技が発動
狙い：必殺技が一人だけで出せるのおかしくね？という意見から。

**Comment by aoi0708** [comment]
UIにパーティクルシステム使えないのですが左上のキャラアイコンのところはどのように実装すればいいですか？

**Comment by okamoto0102** [comment]
@aoi0708 
素材これでお願いします！

![23742544](https://github.com/user-attachments/assets/793d3d94-7c54-45d9-b993-c7860eb0537d)
![23733950](https://github.com/user-attachments/assets/034d3687-2e1c-4624-b2e1-04113c821402)
