### ISSUE TITLE
ボスがノックバックの時に反転する

### ISSUE THREAD

**Issue by okamoto0102** [MiyoshiTaishou/MS2024#886]
### 今の状態を記載
ボスがノックバックした時に反転する。
反転した後の行動がそのまま反転したまま行動することになっている

### 理想の状態を記載
ノックバックした時に反転はしない
（タスク完了の条件になります。）

### アクション
（改善のための具体的なアクションを記載）

### 課題
（現状分かっている課題を記載）

**Comment by MiyoshiTaishou** [comment]
修正しました

**Comment by okamoto0102** [comment]
確認できました！対応ありがとうございます！
